### ISSUE TITLE
Multi Line Use Statements

### ISSUE THREAD

**Issue by michaelcandido** [ejmr/php-mode#100]
Syntax highlighting will fail on all lines after the first line of

use ReflectionMethod,
      ReflectionObject,
      ReflectionProperty;

which is valid and a pretty common pattern in code I've seen. Auto aligning of the names would also be a plus.

**Comment by syohex** [comment]
This issue was fixed.

#### Older version

![older](https://cloud.githubusercontent.com/assets/554281/5956334/379fa29e-a7f0-11e4-8309-6d8bb3be6e2e.png)

#### Latest version

![latest](https://cloud.githubusercontent.com/assets/554281/5956338/3d1e55f8-a7f0-11e4-801a-585c6b139891.png)

**Comment by ejmr** [comment]
@syohex I've made you a collaborator on the project thanks to your efforts going through all of these issues.  You should be able to close them now yourself.  Again, I appreciate it a lot.

**Comment by syohex** [comment]
Thanks.
