### ISSUE TITLE
Typing `function smeg() {` Hangs Emacs

### ISSUE THREAD

**Issue by chrsigg** [ejmr/php-mode#101]
1. Start Emacs using `emacs -Q`
2. Load `php-mode.el`
3. Create new buffer `smeg.php` (which loads `php-mode` successfully)
3. Type `function smeg() {`
4. Emacs hangs after the opening curly brace and needs a `C-g` to recover

This is on:
* Emacs 23.3.1 under Ubuntu 12.04.1 LTS
* From commit db7a98ca8a
* `php-mode-modified` is set to "2013-06-09"
* `*Messages*` contains no helpful information

Let me know what else you need to diagnose the problem.

**Comment by syohex** [comment]
I cannot reproduce this issue on Emacs 23.4.
Please reopen if you still have problems.
