### ISSUE TITLE
Array indent changed after update

### ISSUE THREAD

**Issue by feklee** [ejmr/php-mode#130]
After a recent update to *GNU Emacs 24.3.1 (i386-mingw-nt5.1.2600) of 2013-03-17 on MARVIN* and *php-mode 20130920.1850*, array indent changed. Previously:

    array('a' => 1,
          'b' => 2);

Now:

    array('a' => 1,
    'b' => 2);

How do I get the back the previous indent behavior? I am not sure if this is a bug, or if it is my mistake.

See also my related [post on Github][1].

[1]: http://stackoverflow.com/questions/19000794/php-mode-suddenly-indents-differently

**Comment by syohex** [comment]
@feklee Latest php-mode works as you excected. I close this issue.

![array-indent](https://cloud.githubusercontent.com/assets/554281/6018143/e9c5c83c-abd7-11e4-98ad-71900d686df0.gif)

**Comment by feklee** [comment]
Love the animation. :+1:
