### ISSUE TITLE
Highlight variables inside string

### ISSUE THREAD

**Issue by TatriX** [ejmr/php-mode#136]
Is it possible to highlight variables in the php strings:
```php
echo "There is no $spoon";
```
I would be great if php-mode could highlight ``$spoon``.

**Comment by syohex** [comment]
![php-mode](https://cloud.githubusercontent.com/assets/554281/6018010/d63ded2c-abd6-11e4-82c6-56a62240f000.png)

php-mode already provides this feature.
I closed.
