### ISSUE TITLE
Startup error with latest git HEAD

### ISSUE THREAD

**Issue by flack** [ejmr/php-mode#137]
I'm using Aquamacs (http://aquamacs.org/), which is basically Emacs 23.4.1, and I I can't load the current HEAD version of php-mode. I get the following warning on startup:

```
Warning (initialization): An error occurred while loading `.emacs':

Symbol's function definition is void: syntax-propertize-rules

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

I did a little digging and found that before https://github.com/ejmr/php-mode/commit/b1a6844b0ca679c118a6e3dcf97e9ff31d5be02b, it works normally. I don't know if this only happens on Aquamacs (or the emacs version it uses), but I thought I'd post it anyways :-)

**Comment by syohex** [comment]
This issue should be closed. This issue was fixed and I cannot get this error on Emacs 23.4.

However I suppose php-mode.el drops Emacs 23 support. Because it makes difficult to
maintain and many Emacs users already use Emacs 24.

**Comment by flack** [comment]
Just tested again with current Aquamacs (based on Emacs 24.4.51.2), and it currently works without problems ==> closing

**Comment by ejmr** [comment]
> However I suppose php-mode.el drops Emacs 23 support.

Ideally no, but realistically, yeah, it does.

Thanks guys for the updates.
