### ISSUE TITLE
tab-indentation of multiline comment (docblock) does not work

### ISSUE THREAD

**Issue by cweiske** [ejmr/php-mode#141]
Imagine the following code:
```
<?php
class Foo
{
/*|
}
?>
```

The `|` is the cursor/caret.

When pressing "tab", I expect that the docblock gets indented 4 spaces, just like everything else does. Currently, nothing happens.

This is with php-mode 2f01ed9ed9ce1c562c404bff9d68e81df9b4f1cc and emacs 24.3.1 on Ubuntu Linux 13.10.

I made sure it's a clean environment by running
```
$ emacs -q test.php
```
and then wrote in the *scratch* buffer:
```
(add-to-list 'load-path "~/.emacs.d/php-mode")
(require 'php-mode)
```
Then I switched test.php to php-mode.

**Comment by syohex** [comment]
This issue was already fixed.

Screencast of latest version is here.

![141](https://cloud.githubusercontent.com/assets/554281/6100655/db4bc404-b056-11e4-87e9-a7b50f9b407d.gif)


Thanks for reporting issue.
