### ISSUE TITLE
show-trailing-whitespace does not work with.

### ISSUE THREAD

**Issue by Seraphicer** [ejmr/php-mode#149]
```
(setq-default show-trailing-whitespace t)
```
This setting does not work with php-mode.

I use
```
GNU Emacs 24.3.1 (x86_64-apple-darwin13.1.0)
```

**Comment by syohex** [comment]
`php-mode` should set user default value instead of `nil` other than Drupal.

**Comment by syohex** [comment]
@Seraphicer `php-mode` uses user default value of `show-trailing-whitespace` except
Drupal style. Please check latest version and reopen if you still have problem.
