### ISSUE TITLE
Escaped quote inside string breaks highlighting 

### ISSUE THREAD

**Issue by wyuenho** [ejmr/php-mode#174]
This a regression introduced by #172. Both single and double quotes are affected.

![screen shot 2014-09-27 at 2 51 00 am](https://cloud.githubusercontent.com/assets/160028/4425865/14aaf5a8-45ae-11e4-8d66-289436196f4a.png)

**Comment by syohex** [comment]
This issue should be closed. This issue was fixed.

Screenshot with latest version is here.
![php-mode](https://cloud.githubusercontent.com/assets/554281/5954106/657387c2-a7d6-11e4-93fd-bab0e92d0b83.png)

**Comment by ejmr** [comment]
Thank you for cleaning up these open issues that I should have closed long ago.
