### ISSUE TITLE
Indent of break/return in switch case statements at beginning of line

### ISSUE THREAD

**Issue by etu** [ejmr/php-mode#184]
At first I thought this was a new bug. But then I rolled back to the latest *stable* tag and realized it was an issue back then as well.

Example:
```php
<?php

switch(true) {
    case true:
        echo 'hello';

break;
}
```

If I make a selection of all the text and hit tab, It get's indented correctly (8 spaces). But If I place the cursor on *break*, like anywhere, and hit tab. It won't get indented.

Same with "return". In latest git.

**Comment by emestee** [comment]
Works for me in 1.15.3

**Comment by syohex** [comment]
This issue was already fixed.
Screencast of latest version is here.

![184](https://cloud.githubusercontent.com/assets/554281/6100293/378be354-b050-11e4-8216-c5fb68f3ae36.gif)

Thanks for reporting issue.
