### ISSUE TITLE
Multiple statments inside of switch-case with several labels for the same code

### ISSUE THREAD

**Issue by etu** [ejmr/php-mode#186]
Think this is a new one @jorissteyn ;)

```php
<?php
switch (true) {
    case false:
    case true:
        echo 'Indented with 8 spaces';

    echo 'Indented with 4 spaces';
}
```

If you remove one of the cases the second echo indents correctly.

It seems to look at one statement, regardless if it's a blockstatement or not.
```php
<?php
switch (true) {
    case false:
    case true:
        if (true) {
            echo 'Indented with 8 spaces';
        }

    echo 'Indented with 4 spaces';
}
```

**Comment by syohex** [comment]
This issue was fixed, however its test is wrong.
I'll send PR for fixing test.

**Comment by syohex** [comment]
This issue was already fixed. Screencast of latest version is here.

![186](https://cloud.githubusercontent.com/assets/554281/6100265/5fadb61a-b04f-11e4-88aa-b2511aa6be2b.gif)

Thanks for reporting issue.
