### ISSUE TITLE
[PSR-2] Inconsistent indents of chained method calls

### ISSUE THREAD

**Issue by etu** [ejmr/php-mode#192]
Current:
```php
<?php

$foobar
    ->baz()
    ->bazar();

$foobar->baz()
       ->bazar();

$foo = $bar
    ->baz()
    ->bazar();

$foo = $bar->baz()
           ->bazar();
```

Considered correct:
```php
<?php

$foobar
    ->baz()
    ->bazar();

$foobar->baz()
    ->bazar();

$foo = $bar
    ->baz()
    ->bazar();

$foo = $bar->baz()
    ->bazar();
```

**Comment by krzysztof-magosa** [comment]
Hi ejmr, any chance for fixing it? It still ident chained methods inconsistently :(

**Comment by ejmr** [comment]
Sorry about the delay @krzysztof-magosa.  Would you please fetch the latest changes and try commit 0df42d4bb342c10447db616a33affd03e04f686c (i.e. branch `psr-2-indentation`)?  If that patch helps then I'll work on integrating and merging it ASAP.

**Comment by krzysztof-magosa** [comment]
I've checked branch psr-2-indentation and it works great for me :)

**Comment by ejmr** [comment]
Thanks, glad to hear that.  I will merge it soon then.

**Comment by krzysztof-magosa** [comment]
Thanks a lot ejmr ;-)

**Comment by krzysztof-magosa** [comment]
Just to bump it up ... ;)

**Comment by ejmr** [comment]
Finally merged.

My apologies for the delay.  Some personal matters came up "in real life," and to be honest I must unfortunately admit that I forgot about this as a result.  Thank you @krzysztof-magosa for your patience.

**Comment by krzysztof-magosa** [comment]
You spend private time for community, so great thanks for your effort ejmr and no worries!
I'll do update immediately, php-mode does really good work ;-)

Thanks again.
