### ISSUE TITLE
Function named "string" not hightlighted correctly

### ISSUE THREAD

**Issue by jdufresne** [ejmr/php-mode#197]
With the latest version of php-mode and the following test case:

```
<?php

$obj->string();
$obj->func();
```

I would expect `string()` and `func()` to be highlighted identically. However, `string()` is highlighted as if it is a type, not a function.

**Comment by syohex** [comment]
This issue was fixed.

#### Older version v1.14
![old](https://cloud.githubusercontent.com/assets/554281/5973300/fca7a1ae-a8a9-11e4-9dbe-0e6bb44da4be.png)


#### Latest version
![new](https://cloud.githubusercontent.com/assets/554281/5973303/ff5b2c0e-a8a9-11e4-9e37-bb4e58835b8d.png)
