### ISSUE TITLE
$this no longer highlighted differently than other variables

### ISSUE THREAD

**Issue by jdufresne** [ejmr/php-mode#201]
Please look at the example below:

`$this` used to be highlighted differently than other variables, but now it is highlighted as a normal variable. If you compare this with other modes, such as `c++-mode`, you'll see this is not the typical convention. In `c++-mode` `this` is highlighted differently (as a keyword). FWIW, I appreciate the distinction between `$this` and a normal variable.

```
<?php

class MyClass
{
    public function foo()
    {
        $this->bar();
    }
}
```

**Comment by syohex** [comment]
This issue was fixed.

![php-mode-this](https://cloud.githubusercontent.com/assets/554281/6002533/7ad3b614-ab37-11e4-877d-7dbd38d9d076.png)
