### ISSUE TITLE
Adjust Minimum Emacs Version?

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#214]
Issue #86 made me think of this.  Currently the README says that PHP Mode requires GNU Emacs 23.1 or later.  Should we continue to maintain support for that version, or should we make Emacs 24 the new baseline.  Personally I am in favor of making the change to require Emacs 24.  But before doing so I want to hear from users about what versions they use, as well as any pros and cons we would inherit by dropping support for Emacs 23.

**Comment by syohex** [comment]
I agree with dropping Emacs 23 support.

Pros
- Easy to maintain
- Better performance by lexical-binding

It is not easy to install old Emacs.  Old Emacs cannot be build with recent compiler and libc
without any patches.

A few users who uses Emacs 23 cannot use php-mode if we drop Emacs 23 support.
I think many users already use Emacs 24 or higher, so this is not matter much.

After Emacs 24.4 released, many packages drops Emacs 23 support.
If users use such packages, they should upgrade Emacs version.

**Comment by ejmr** [comment]
> After Emacs 24.4 released, many packages drops Emacs 23 support.

I am hearing this same thing from some people I've spoken with, which is making me think we should drop Emacs 23 support.  Although I'm not in a rush to make the change.  But my early impression is that it's a change worth making eventually.

**Comment by jorissteyn** [comment]
FYI: php-mode in master has been broken for emacs 23 since at least october last year due to the cl/cl-lib workaround for newer versions that don't take < 24 into account.

**Comment by ejmr** [comment]
@jorissteyn Thanks for letting me know.  So would you be in favor then of dropping support for Emacs 23?

**Comment by jorissteyn** [comment]
Yes absolutely!

**Comment by andreas-roehler** [comment]
AFAIU there is no explicit Emacs 23 support. It's just not broken.

Beside of some minor c-mode issues  - which would deserve a fix and separate ticket anyway.

Checked with GNU Emacs 23.4.1 (i686-pc-linux-gnu, GTK+ Version 2.24.21) of 2013-10-25 on akateko, modified by Debian

So why not keep it?

Personally see no need for lexical-binding here - if there is some, that would change the game.

**Comment by ejmr** [comment]
> AFAIU there is no explicit Emacs 23 support. It's just not broken. [...] So why not keep it?

If there are features implemented in PHP Mode which require functionality not available in Emacs 23 then personally I don't want that to hold back those features.  In my opinion, ensuring that PHP Mode works with Emacs 23 is not a compelling reason to reject any patches which would break support for that version.

**Comment by andreas-roehler** [comment]
Am 29.07.2015 um 08:38 schrieb Eric James Michael Ritz:
>
>     AFAIU there is no explicit Emacs 23 support. It's just not broken.
>     [...] So why not keep it?
>
> If there are features implemented in PHP Mode which require 
> functionality not available in Emacs 23 then personally I don't want 
> that to hold back those features. In my opinion, ensuring that PHP 
> Mode works with Emacs 23 is not a compelling reason to reject any 
> patches which would break support for that version.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ejmr/php-mode/issues/214#issuecomment-125858571>.
>

Agreed. Just for curiosity: could you point at some patch, which would 
break Emacs 23?

**Comment by ejmr** [comment]
> Agreed. Just for curiosity: could you point at some patch, which would break Emacs 23?

Everything related to ERT, but that's only for the test suite.  With regard to `php-mode.el` itself, I can't think of anything off the top of my head which breaks under Emacs 23.  Ideally I would like PHP Mode to work with Emacs 23 for as long as possible, but if sometime in the future a person submits a patch that doesn't work with Emacs 23 then I wouldn't reject it for that reason alone.  Also, if anyone wants to invest the effort to ensure PHP Mode continues to work with Emacs 23 in the future then that would earn great appreciation from me.

**Comment by andreas-roehler** [comment]
Am 29.07.2015 um 09:26 schrieb Eric James Michael Ritz:
>
>     Agreed. Just for curiosity: could you point at some patch, which
>     would break Emacs 23?
>
> Everything related to ERT, but that's only for the test suite. With 
> regard to |php-mode.el| itself, I can't think of anything off the top 
> of my head which breaks under Emacs 23. Ideally I would like PHP Mode 
> to work with Emacs 23 for as long as possible, but if sometime in the 
> future a person submits a patch that doesn't work with Emacs 23 then I 
> wouldn't reject it for that reason alone. Also, if anyone wants to 
> invest the effort to ensure PHP Mode continues to work with Emacs 23 
> in the future then that would earn great appreciation from me.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ejmr/php-mode/issues/214#issuecomment-125868800>.
>

Sounds good, thanks.
