### ISSUE TITLE
before-save-hook no longer working

### ISSUE THREAD

**Issue by flack** [ejmr/php-mode#215]
I've recently updated from 1.13.1 to current HEAD, and since then, the `before-save-hook` from my `.emacs` file is not working any longer. I use the following setup code:

```lisp
(load "~/.emacs.d/php-mode.el")

(defun my-php-mode ()
  "change code style"
  (c-set-style "awk")
)

(add-hook 'php-mode-hook 'my-php-mode)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
```

Is this some error on my part or a regression of some sort?

**Comment by syohex** [comment]
`before-save-hooks` works. But `delete-trailing-whitespace` is removed from 
`before-save-hook` at #147. I think that change is not good. `php-mode` should not remove
it from before-save-hook and user should judgement it.

**Comment by flack** [comment]
I've looked at that ticket, but can't really understand the rationale. Is there a suggested workaround? The problem is that this does not only affect PHP files, but really anything you open in emacs

**Comment by syohex** [comment]
Workaround is here. I'll send PR about this issue later.

```lisp
(require 'php-mode)

(defun my-php-mode ()
  "change code style"
  (c-set-style "awk")
  (add-hook 'before-save-hook 'delete-trailing-whitespace))

(custom-set-variables
 '(php-mode-force-pear t))
(add-hook 'php-mode-pear-hook 'my-php-mode)
```

**Comment by syohex** [comment]
@flack Please check latest version. It is not necessary to use above workaround with latest version.

**Comment by flack** [comment]
@syohex Tested again with latest HEAD and it's working like a charm. Thanks for the quick fix!
