### ISSUE TITLE
Auto-Complete popup aligns incorrectly in php-mode.

### ISSUE THREAD

**Issue by aaronbieber** [ejmr/php-mode#220]
At some point fairly recently, auto-complete popups started to display as though the text of the popup is wrapped as normal text (they would sit at the end of existing text lines below point). I have included some screenshots here.

Though I don't wish for this to be `php-mode`'s problem, it doesn't happen in `text-mode` or `lisp-interaction-mode`, as seen in the following screenshots.

Broken in `php-mode`:
![image](https://cloud.githubusercontent.com/assets/157664/6002357/90d36fe4-aac0-11e4-99f4-c30691492ff1.png)

Working in `text-mode`:
![image](https://cloud.githubusercontent.com/assets/157664/6002361/976bda1c-aac0-11e4-9f23-5d78f8dc54ea.png)

Working in `lisp-interaction-mode`:
![image](https://cloud.githubusercontent.com/assets/157664/6002366/9b4e4304-aac0-11e4-8676-5a6378fb2de7.png)

I'm happy to provide whatever additional information would be helpful. I'm using the latest MELPA version of `php-mode` (20150131...), `php-mode-version-number` is 1.15.3.

**Comment by syohex** [comment]
I cannot reproduce this issue.
![php-auto-complete](https://cloud.githubusercontent.com/assets/554281/6002465/e1e0500c-ab36-11e4-97d4-00548af3086e.png)

Would you show us configuration of `auto-complete` and `php-mode` ?

**Comment by aaronbieber** [comment]
This is the only configuration that I have done, and it hasn't changed in quite a long time. I have all of my configuration files in git, so I rolled back to a version about a month old and the problem persisted, though it just started happening quite recently.

```
(defun configure-php-mode ()
  (require 'newcomment)
  (setq comment-auto-fill-only-comments 1)
  (setq auto-fill-function 'do-auto-fill)

  (c-set-style "wf-php")
  (turn-on-eldoc-mode)
  (highlight-symbol-mode)

  (turn-on-auto-fill)
  (set-fill-column 120)
  (turn-on-fci-mode)
  (add-to-list 'write-file-functions 'delete-trailing-whitespace)
  (gtags-mode t)

  (define-key evil-normal-state-map (kbd "_") 'selective-display-decrease)
  (define-key evil-normal-state-map (kbd "+") 'selective-display-increase))

(add-hook 'php-mode-hook 'configure-php-mode)
```

**Comment by aaronbieber** [comment]
I deleted my entire `~/.emacs.d/elpa` directory and re-downloaded and re-compiled all packages and it seems like the problem has gone away. I will close this issue and sorry for the wild goose chase.

**Comment by aaronbieber** [comment]
I spoke too soon. It stopped happening in a scratch buffer changed to `php-mode`, but still happens in my usual project files. I will try to narrow this down further, perhaps it is related to some other mode or setting that is different between these two buffers.

**Comment by aaronbieber** [comment]
All of the modes enabled are identical between the buffer where the alignment is working and the buffer where it is not. I am at a loss for what else to check. Any help would be appreciated.

**Comment by aaronbieber** [comment]
The issue is still happening in the scratch buffer, but in order to see it, I had to start a completion above other lines. Here is another image of what is happening. I'm attempting to debug `popup.el`, but my Lisp is not strong.

![image](https://cloud.githubusercontent.com/assets/157664/6005002/ff53a560-aad4-11e4-99ff-3dc3a9244038.png)

**Comment by emestee** [comment]
Make sure your code style in the file buffer is the same as in the scratch buffer. The difference between styles may account for the phenomenon.

**Comment by syohex** [comment]
This is why `popup.el` does not work with `fill-column-indicator`.
`php-mode` is unrelated.
