### ISSUE TITLE
(use-package php-mode :ensure t) in init.el causes a startup error

### ISSUE THREAD

**Issue by Zalewa** [ejmr/php-mode#231]
Following is a minimal init.el that when dumped into a clean ~/.emacs.d will install php-mode properly, but upon future program restarts will cause errors:
```elisp
;; Load packages.
(require 'package)
(add-to-list 'package-archives
  '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(if (not (package-installed-p 'use-package))
    (progn
      (package-refresh-contents)
      (package-install 'use-package)))

(require 'use-package)

(use-package php-mode :ensure t)
```

Contents of the error produced by --debug-init:

```
Debugger entered--Lisp error: (void-function set-difference)
  signal(void-function (set-difference))
  byte-code("\303\304	#\210\305!\210\306\n@\nA\"\207" [sym mode err message "Eval error in the `c-lang-defconst' for `%s' in %s:" makunbound signal] 4)
  c-get-lang-constant(c-matchers-2 (cc-fonts) php-mode)
  (defconst php-font-lock-keywords-2 (c-get-lang-constant (quote c-matchers-2) (quote (cc-fonts)) (quote php-mode)) ("/home/test/.emacs.d/elpa/php-mode-20150304.716/php-mode.elc" . 37987))
  require(php-mode nil t)
  (not (require (quote php-mode) nil t))
  (if (not (require (quote php-mode) nil t)) (message "Could not load package %s" "php-mode") nil nil nil t)
  (if (and (boundp (quote use-package-verbose)) use-package-verbose) (let ((now (current-time))) (message "%s..." "Loading package php-mode") (prog1 (progn (if (not (require (quote php-mode) nil t)) (message "Could not load package %s" "php-mode") nil nil nil t)) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed (or (and ... use-package-minimum-reported-time) "0.01")) (message "%s...done (%.3fs)" "Loading package php-mode" elapsed) (message "%s...done" "Loading package php-mode"))))) (if (not (require (quote php-mode) nil t)) (message "Could not load package %s" "php-mode") nil nil nil t))
  (if (and t t) (if (and (boundp (quote use-package-verbose)) use-package-verbose) (let ((now (current-time))) (message "%s..." "Loading package php-mode") (prog1 (progn (if (not (require ... nil t)) (message "Could not load package %s" "php-mode") nil nil nil t)) (let ((elapsed (float-time ...))) (if (> elapsed (or ... "0.01")) (message "%s...done (%.3fs)" "Loading package php-mode" elapsed) (message "%s...done" "Loading package php-mode"))))) (if (not (require (quote php-mode) nil t)) (message "Could not load package %s" "php-mode") nil nil nil t)))
  (progn nil (quote nil) (if (and t t) (if (and (boundp (quote use-package-verbose)) use-package-verbose) (let ((now (current-time))) (message "%s..." "Loading package php-mode") (prog1 (progn (if (not ...) (message "Could not load package %s" "php-mode") nil nil nil t)) (let ((elapsed ...)) (if (> elapsed ...) (message "%s...done (%.3fs)" "Loading package php-mode" elapsed) (message "%s...done" "Loading package php-mode"))))) (if (not (require (quote php-mode) nil t)) (message "Could not load package %s" "php-mode") nil nil nil t))))
  eval-buffer(#<buffer  *load*> nil "/home/test/.emacs.d/init.el" nil t)  ; Reading at buffer position 331
  load-with-code-conversion("/home/test/.emacs.d/init.el" "/home/test/.emacs.d/init.el" t t)
  load("/home/test/.emacs.d/init" t t)
  #[0 "\205\262
```

emacs version: 24.4.1
php-mode version: 20150304.716

**Comment by syohex** [comment]
I cannot reproduce this issue. `php-mode.el` does not use `set-difference` function
for Emacs 24.4 and it uses `cl-set-difference`. So I don't understand why did you get such error ?

Could you check whether you get same error by `emacs-24.4 -Q -l ~/.emacs.d/elpa/php-mode-20150304.716/php-mode.el` ? If you don't get error, please retry after uninstalling
php-mode.el.

**Comment by ejmr** [comment]
I also cannot reproduce this using GNU Emacs 24.4.1 (i686-pc-linux-gnu, GTK+ Version 3.10.8).

**Comment by Zalewa** [comment]
@syohex I used your command and there's no error.

I made a video showing the problem occuring on a Lubuntu virtual box and on a Windows machine:
https://www.youtube.com/watch?v=Hlw98X7koGo

**Comment by syohex** [comment]
I got same error when php-mode was byte-compiled by Emacs 24.3 and it is loaded
by Emacs 24.4. Please remove `php-mode.elc`  and retry.

**Comment by Zalewa** [comment]
@syohex This helps solve the issue. php-mode seems to be working correctly now and the error is gone. So, it seems that .elc file is downloaded from melpa and it's a packaging issue then.

**Comment by syohex** [comment]
> So, it seems that .elc file is downloaded from melpa and it's a packaging issue then.

No. You download only `.el` file and `.elc` is generated on your machine.

**Comment by Zalewa** [comment]
@syohex Then why is the .elc file wrong? I haven't migrated it from a previous emacs version. I clean the entire .emacs.d directory and the bug gets reproduced everytime I exec my example init.el. Also, when I deleted the .elc files, emacs doesn't recreate them upon restart.

**Comment by syohex** [comment]
> Then why is the .elc file wrong?

I don't know. I install several emacs but I never got this error.
And I and @ejmr cannot reproduce this issue, so I suppose there are some problems on
your environment. Please uninstall old Emacs(Emacs24.3) and retry if possible.

**Comment by Zalewa** [comment]
Out of 4 installations I tested this on I got only one where the problem didn't occur. It was an Ubuntu 14.04 machine. The others are one that runs Lubuntu 14.04 and two that run Windows 7. I just tried deleting all emacs files and reinstalling as you suggested but it didn't help. On Windows all emacs files (besides .emacs.d dir) are located in a single directory so it's impossible to screw this up. On Linux I'm unaware if emacs source package has any means of automatic uninstallation so I manually deleted contents of all directories in /usr/local as mentioned by INSTALL readme file. I also deleted all packages mentioned by `dpkg -l | grep emacs`. No avail; problem still exists.

My elisp knowledge is nearly non-existent, otherwise I'd try to debug it myself at this point. I'm not even sure how to read the backtrace produced by --debug-init.

**Comment by syohex** [comment]
Would you show us how to reproduce this issue in detail ?
- How to construct environment where this issue occurs.
- How to install Emacs.
etc

I cannot reproduce this issue. I cannot get error as below.

![php-mode](https://cloud.githubusercontent.com/assets/554281/6545768/d7697f5e-c5da-11e4-9064-088ff5bb49b4.gif)

**Comment by Zalewa** [comment]
22 steps to reproduce the problem:

````
1. Install Ubuntu 14.04 64-bit on a virtual box. Name of my ISO:
   'ubuntu-14.04.1-desktop-amd64.iso'.
   md5 sum: 119cb63b48c9a18f31f417f09655efbd
3. Pick "English" language. Pick "Polish" keyboard layout.
4. User: test, Password: 1
5. sudo apt-get update
6. sudo apt-get install gnome-session-fallback
7. Switch from unity to gnome compiz
8. sudo apt-get build-dep emacs
9. sudo apt-get build-dep emacs24
10. wget http://ftp.task.gda.pl/pub/gnu/emacs/emacs-24.4.tar.gz
11. tar -xvzf ./emacs-24.4.tar.gz
12. cd ./emacs-24.4
13. ./configure
14. make -j 6
15. sudo make install
16. Emacs is now installed. Run it: `emacs`.
17. Close emacs.
18. mcedit ~/.emacs.d/init.el
19. copy&paste my example init.el & save
20. run emacs; wait for startup to complete.
21. shutdown emacs.
22. run emacs again.
````

**Comment by zonuexe** [comment]
I was able to reproduce the problem.

GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2015-03-08 on ubuntu

![2015-03-09 0 19 09](https://cloud.githubusercontent.com/assets/822086/6546291/f72f0fe0-c5f1-11e4-8594-c0db0030abbe.png)

**Comment by syohex** [comment]
I can reproduce

**Comment by syohex** [comment]
This issue occurs on only Emacs 24.4. I cannot reproduce this on Emacs 24.3 and Emacs development version.

**Comment by syohex** [comment]
@Zalewa  @zonuexe I have applied workaround at #232. Please check latest version.

**Comment by zonuexe** [comment]
:+1:

**Comment by Zalewa** [comment]
Problem seems to be fixed. Thank you.
