### ISSUE TITLE
Cannot open load file: no such file or directory, init

### ISSUE THREAD

**Issue by KryDos** [ejmr/php-mode#243]
Hi Guys,

I have reinstalled my os (osx) and installed emacs. Now I'm trying to install php-mode but I'm getting this error
```
Cannot open load file: no such file or directory, init
```
This is what I see in \*Messages\* buffer:
```
Eval error in the `c-lang-defconst' for `c-simple-stmt-kwds' in php-mode:
Eval error in the `c-lang-defconst' for `c-keywords' in php-mode:
Eval error in the `c-lang-defconst' for `c-regular-keywords-regexp' in php-mode:
Eval error in the `c-lang-defconst' for `c-basic-matchers-before' in php-mode:
Eval error in the `c-lang-defconst' for `c-matchers-2' in php-mode:
```
Could you please help me with it?

**Comment by syohex** [comment]
Which emacs version do you use ?
You can check it by `M-x emacs-version`.

**Comment by KryDos** [comment]
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

**Comment by syohex** [comment]
How do you install php-mode ?

**Comment by KryDos** [comment]
via M-x package-install

php-mode-20150414.707 - it's folder name where php-mode is installed right now...

I think it was installed from melpa repository and was published in 2015-04-14 (according to folder name)

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue with Emacs 24.5.1 on my MacOSX.

Would you reinstall php-mode after uninstalling or removing php-mode ?

**Comment by KryDos** [comment]
Already try to remove php-mode and install it again.

Let me try to reinstall Emacs completely. I'll update you in couple of minutes.

**Comment by KryDos** [comment]
I reinstalled Emacs and now it works. 

I didn't remove .emacs.d folder where php-mode was installed. So nothing was changed in .emacs.d folder. But it works after reinstallation. 

It's absolutely doesn't seem like php-mode issue. Sorry for confusion :(

**Comment by schnecki** [comment]
I had to delete and then reinstall php-mode to get it working. Weird thing.

**Comment by creamidea** [comment]
I have met the same problem. And I do <kbd>M-x</kbd> and then type `package-reinstall` to reinstall *php-mode*. At last, everything is OK. Thx~
