### ISSUE TITLE
revert-buffer seems to break imenu/speedbar

### ISSUE THREAD

**Issue by trashofmasters** [ejmr/php-mode#244]
Opening a file with a bunch of function declarations shows each function name under the imenu/speedbar `Named Functions` group.

If one uses `revert-buffer`/`C-x C-v` to revert the buffer, this will cause all function declarations to disappear until the buffer is killed and the file reopened.

I am experiencing this issue with ECB/Speedbar on Emacs 24.4 using last PHP-mode `049102f9`

**Comment by ejmr** [comment]
Clean you please provide a test file or snippet of code I can use to try and duplicate this bug?

**Comment by trashofmasters** [comment]
Yes I will after work. Sorry for the rushed report.

**Comment by ejmr** [comment]
No worries, no need to apologize.

**Comment by trashofmasters** [comment]
I have found the minimal configuration required to reproduce my issue in `emacs -Q`.

Firstly, this issue only happens when `C-x C-c` (`find-alternate-file`) is used.

Secondly, the problem seem to only exist in Ecb, not Speedbar or imenu, and it might be even solved by forcing the redraw of Ecb's methods window. To be honest I haven't tried as I don't recall the function or its binding.

I'm happy to close this issue for the time being. If you want I can add a more detailed reproduction scenario.

**Comment by trashofmasters** [comment]
Okay, as I was suspecting the solution to this very problem is rather simple.

The ECB manual suggests that rebuilding the methods buffer should never be required, but the described misbehaviour can be resolved with `ecb-rebuild-methods-buffer`, which is normally bound to `C-c . r`.
