### ISSUE TITLE
feature request - disable intepolated-variable

### ISSUE THREAD

**Issue by fxbois** [ejmr/php-mode#248]
It would be great to provide a mechanism to disable ```php-annotations-font-lock-find-annotation``` and ```php-string-intepolated-variable-font-lock-find```
Perhaps provide a ```php-disable-extra-fontification``` which could be used in the ```eval-after-load```

**Comment by ejmr** [comment]
If we're going to have a feature to toggle "extra" fontification on or off (which I think is a good idea), then is there anything else that you or anyone else feels should be part of that "extra" group of font-lock definitions that we have?

**Comment by fxbois** [comment]
Should we use this new flag to disable html elements detection ?
