### ISSUE TITLE
Emacs-git not supported

### ISSUE THREAD

**Issue by dertuxmalwieder** [ejmr/php-mode#249]
In this year's Emacs builds, they renamed a function, making `php-mode` basically not working:

> Symbol's function definition is void: c-change-set-fl-decl-start

Please fix that. :)

**Comment by syohex** [comment]
I cannot reproduce this issue. I suppose you use old byte-compiled file.
Please try again after removing old byte-compiled file and recompiling.

**Comment by dertuxmalwieder** [comment]
Indeed. *cough*
