### ISSUE TITLE
Tests against Emacs 23

### ISSUE THREAD

**Issue by andreas-roehler** [ejmr/php-mode#262]
As core of php-mode seems compatible with Emacs 23,  will consider to contribute some tests.

**Comment by ejmr** [comment]
Thanks, this would be great to have.  As far as ERT goes, my understanding is that an older version/back-port is available for Emacs 23, but I've heard it has some major differences compared to the ERT that comes packaged with Emacs 24 and later.  However, I've never tried using ERT with Emacs 23 so I honestly can't say how true that is or not.

**Comment by andreas-roehler** [comment]
Am 29.07.2015 um 10:03 schrieb Eric James Michael Ritz:
>
> Thanks, this would be great to have. As far as ERT goes, my 
> understanding is that an older version/back-port is available for 
> Emacs 23,
>

Yes, but that probably really isn't worth the time. Whould write some 
plain calls to "should" from function.

**Comment by andreas-roehler** [comment]
Resp. "assert" - "should" is the ert-thing.
