### ISSUE TITLE
eval-buffer fails at php-mode-test.el

### ISSUE THREAD

**Issue by andreas-roehler** [ejmr/php-mode#264]
Current implementation of php-mode-test-dir is not reliable, when interactively evaluated,
load-file-name doesn't exist

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  (expand-file-name "tests" (file-name-directory load-file-name))
  (defvar php-mode-test-dir (expand-file-name "tests" (file-name-directory load-file-name)) "Directory containing the `php-mode' test files.")
  eval-buffer()  ; Reading at buffer position 1396
  call-interactively(eval-buffer record nil)
  command-execute(eval-buffer record)
  execute-extended-command(nil "eval-buffer")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by syohex** [comment]
It should not be relative path. You should use `default-directory` if `load-file-name` is nil as below.

```diff
diff --git a/php-mode-test.el b/php-mode-test.el
index a510273..1806a86 100644
--- a/php-mode-test.el
+++ b/php-mode-test.el
@@ -39,7 +39,10 @@
 ;; <http://debbugs.gnu.org/cgi/bugreport.cgi?bug=14325>.
 (c-after-font-lock-init)
 
-(defvar php-mode-test-dir (expand-file-name "tests" (file-name-directory load-file-name))
+(defvar php-mode-test-dir (expand-file-name "tests"
+                                            (if load-file-name
+                                                (file-name-directory load-file-name)
+                                              default-directory))
   "Directory containing the `php-mode' test files.")
 
 (defvar php-mode-test-valid-magics '(indent)
```
