### ISSUE TITLE
Don't customize font-lock-maximum-decoration

### ISSUE THREAD

**Issue by wasamasa** [ejmr/php-mode#270]
Unlike the majority of variables `php-mode`'s body is touching, this one isn't set to a buffer-local value or inherently buffer-local, but a value only the user is supposed to customize, as it does globally control to which extent a programming buffer is fontified. Please remove this line entirely.

**Comment by ejmr** [comment]
We could (and should) improve on it by, for example, checking to see if the user already has a value for `font-lock-maximum-decoration` and, if so, not changing it.  Or if it's a list then checking to see if there's a setting for `php-mode`, and if not then adding that.

> ...but a value only the user is supposed to customize...

Does any of the official documentation mandate that modes should *never* affect `font-lock-maximum-decoration`?

**Comment by syohex** [comment]
I suppose php-mode need not to change `font-lock-maximum-decoration`. Its default value is `t` and almost users don't change its value.

**Comment by ejmr** [comment]
> Its default value is `t`...

Thanks, didn't know that.  In that case we should definitely remove that line.

**Comment by syohex** [comment]
@wasamasa We removed it. Thanks for reporting.
