### ISSUE TITLE
Info on how to use the skeletons?

### ISSUE THREAD

**Issue by kostajh** [ejmr/php-mode#273]
The skeletons look quite useful, only, I can't figure out how to make use of them.

If I look in the directory downloaded from MELPA, I don't see a "skeletons" directory. If I clone the php-mode repo, and add `php-ext.el` to my load path, I still don't see any M-x skeleton commands. I must be missing something obvious; could anyone help? thanks!

**Comment by syohex** [comment]
Please check `M-x php-class`, `M-x php-try-catch` etc.

> If I look in the directory downloaded from MELPA, I don't see a "skeletons" directory

We should fix this. However skelton work is WIP. Some of them does not complete. Should we fix MELPA recipe now or after all works are finished ?

**Comment by kostajh** [comment]
I had to add this to my config:

```
(setq php-ext-path "~/src/php-mode/skeleton/")
(load "~/src/php-mode/skeleton/php-ext.el")
```

Without setting `php-ext-path`, loading `skeleton/php-ext.el` fails.

IMO, it would make sense to include the Skeleton work in MELPA, but if not, then it would probably be good to update the README to avoid confusion.


Syohei YOSHIDA writes:

> Please check `M-x php-class`, `M-x php-try-catch` etc.
>
>> If I look in the directory downloaded from MELPA, I don't see a "skeletons" directory
>
> We should fix this. However skelton work is WIP. Some of them does not complete. Should we fix MELPA recipe now or after all works are finished ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ejmr/php-mode/issues/273#issuecomment-139519475

--
kosta@kostaharlan.net

**Comment by syohex** [comment]
I send PR for updating MELPA php-mode recipe which includes php-mode and skeleton files . https://github.com/milkypostman/melpa/pull/3106

**Comment by ejmr** [comment]
@syohex We can close this issue now, correct?

**Comment by syohex** [comment]
Yes.
