### ISSUE TITLE
Test failures on Emacs 25 on Mac OS 10.11.1

### ISSUE THREAD

**Issue by dunn** [ejmr/php-mode#279]
I haven't had time to look into this closely, but I'm currently seeing two test failures on the latest Emacs (https://github.com/emacs-mirror/emacs/commit/9db11fa2d635935318364370f31821023c2501b9).

Logs: https://gist.github.com/dunn/25824c76a4c9b9373bbb
```
2 unexpected results:
   FAILED  php-mode-test-issue-144
   FAILED  php-mode-test-issue-184

**Comment by ejmr** [comment]
Thank you for the bug report and detailed log info.  Just off the top of my head, I wonder if the problem with test 184 is in any way related to #277.

**Comment by syohex** [comment]
Return value of `(c-guess-basic-syntax)`  [here](https://github.com/ejmr/php-mode/blob/de0d05894232109fd8d77baa28ca0fdc5d9650ea/tests/issue-144.php#L13) is different between Emacs 24 and 25.

Emacs 24 returns `((statement-block-intro 203))` while Emacs 25 returns `((topmost-intro 203))`.

**Comment by syohex** [comment]
Tests were broken at https://github.com/emacs-mirror/emacs/commit/3928ef2dd5b8febf3b1d9c1bfb22af3698d16bea

**Comment by syohex** [comment]
I have applied workaround at #294.
