### ISSUE TITLE
php-mode is slow

### ISSUE THREAD

**Issue by etu** [ejmr/php-mode#28]
When having a big file, my file here is 213, not very long lines.

With php-mode, it's slow to just move around in the file. Lagging when holding the arrow-key for instance.

213 lines is a quite small file in many projects...

I tried to byte-compile php-mode, did help a bit. I think. But not much. Say for example, html-mode is much much faster in the same file.

Does not seem to matter if there's acctualy php in the file, I can take the scratchbuffer, make some copies so the buffer get some size. Enable php-mode and bam, it's slow.

**Comment by emestee** [comment]
This probably should be closed given how there's been no evidence for this being a php-mode problem for 3 years...

**Comment by syohex** [comment]
I don't feel slow when I open the 3000 lines PHP file.
Please reopen this issue. If you still have problems.
