### ISSUE TITLE
(require 'php-mode) breaks rainbow-delimiters-mode + lisp-extra-font-lock-mode

### ISSUE THREAD

**Issue by fallchildren** [ejmr/php-mode#280]
I have no idea why but `(require 'php-mode)` breaks the font-lock stuff rainbow-delimiters-mode (https://github.com/Fanael/rainbow-delimiters) and lisp-extra-font-lock-mode (https://github.com/Lindydancer/lisp-extra-font-lock) bring. And that not only in php-mode but in every other mode.

Before:
![2015-10-30 16_59_15-debian 8 ics gui - vmware workstation](https://cloud.githubusercontent.com/assets/8593587/10850842/0410ff58-7f28-11e5-8e7e-7712707af3dc.png)
After:
![bugwo](https://cloud.githubusercontent.com/assets/8593587/10850845/08c7b000-7f28-11e5-98c6-0e08c7c1fc2a.png)

To reproduce:
- require php-mode
- in your scratch buffer type `'(?\) ?\])`
- turn on rainbow-delimters-mode
  -> normally the escaped parantheses are ignored and not highlighted. Now they are and the last one is marked as error
- turn on lisp-extra-font-lock-mode
  -> normally the whole sexp should get the face `lisp-extra-font-lock-quoted` but now only the part between the first paren and the first escaped paren gets this face

I don't now what is happening here but it sounds like php-mode redefines some internal function used by both packages.

**Comment by ejmr** [comment]
I use Rainbow Delimiters Mode and haven't run into this issue.  Could you please let me know exactly which versions of Rainbow and PHP Mode you're using?  It will help track down any conflicting code.

As for lisp-extra-font-lock-mode, I've personally never used it.  My impression---although I admit I could be wrong---is that it doesn't seem like a mode meant to be used with PHP Mode or any non-Lisp mode anyway.

Or do you mean that activating PHP Mode, Rainbow, and lisp-extra-font-lock-mode breaks the latter *everywhere* for all modes?  If that's the case, then like you my first guess would be we have some conflicting code somewhere.

**Comment by fallchildren** [comment]
I'm using the latest melpa packages of all three packages.

Sorry for the misunderstanding but of course I use the lisp-extra-font-lock mode only in lisp related modes. I am using rainbow-delimiters also only in lisp related buffers.

To make the issue clear:
If php-mode.el is loaded (with ```(require 'php-mode)``` or with autoload) it breaks the functionality in my lisp related modes (I can't say for others as I use those modes only in lisp related buffers)

If I comment out ```(require 'php-mode)``` in my init.el everything is fine until I call ```php-mode``` in any other buffer (like opening a php file with php-mode breaks my scratch buffer with ```lisp-interaction-mode```)

I hope i could make it a bit clearer.

**Comment by Fanael** [comment]
Regression introduced in 55676e80c9907d58d0f8cf37168f18927297b1aa. It *really* is a bad idea to advise font-lock internals globally like this. Please set text properties in `syntax-propertize-function` instead.

**Comment by ejmr** [comment]
Thank you @fallchildren for the info and thank you @Fanael for finding the regression for us---I appreciate it.

I'm busy this weekend and honestly I am not very familiar with using `syntax-propertize-function`, so I'm going to be studying the documentation to make sure I deal with the issue as best as possible.  My goal is to have a patch fixing this bug (and some others) done by no later than Monday, assuming no one else submits a fix before then.

Thank you both for the very useful details, and my apologies for (most likely) not having the time this Saturday and Sunday to write a fix.

**Comment by syohex** [comment]
Is this still problem ?

**Comment by fallchildren** [comment]
just checked. Still is.

To check yourself enable rainbow-delimiters in scratch and type something like
`(?\) ?\()`

and then require php-mode -> font-lock will be broken

**Comment by Fanael** [comment]
It is. Not fixing a bug typically makes the bug being, well, not fixed.
