### ISSUE TITLE
Add ac-php to PHP Mode

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#285]
This task is to fold [ac-php](https://github.com/xcwen/ac-php/) into PHP Mode so that it will be available to users out-of-the-box.  This idea comes from #284 and the author of ac-php [agrees it would be a good idea](https://github.com/xcwen/ac-php/issues/11).

I'm open to suggestions about how to include ac-php, specifically on a technical level.  Naturally we will also have to update the README with documentation explaining that ac-php is available for use and provide an example on how to enable it.

**Comment by syohex** [comment]
I disagree this idea.

- Every people don't use auto-complete, some people use company-mode. 
- We can install both packages easily with package manger like package.el, el-get, Cask.
- Large package makes maintenance difficult. Package should be small as possible.
- I thinks it is good idea if ac-php has heavy dependence on php-mode. But it doesn't.

What are advantages of integrating ac-php ?

**Comment by ejmr** [comment]
I use Company Mode myself, so I agree with you on that point.

The advantage, in my opinion, is that we would be providing auto-completion source (possibly) without any additional setup for the user, or at least with less setup; I'd like to see Company Mode supported the same way.

I also agree with you that smaller packages are better.  I should have been more specific and clarified that it is *not* my intention for us to take over maintenance of ac-php, or any other third-party PHP package.  I feel like we could accomplish including ac-php (and other third-party packages) by implementing and documenting some small utility commands in PHP Mode which use package.el, el-get, etc., to fetch ac-php on behalf of the user.  Or to put it another way, we would "include" ac-php by providing something like a simple option flag or command that would grab and install ac-php *outside* of PHP Mode, but automatically setup the appropriate hooks and such.

**Comment by ejmr** [comment]
To further elaborate and brainstorm, perhaps we add a `php-mode-completion-backend` custom variable with options like ac-php and Company, and if the user does not have them installed then we fetch them through Emacs' package manager for them.

**Comment by trashofmasters** [comment]
I am with @syohex on avoiding integration of php-mode with auto-complete. 

On the other hand, for those who use the package, maybe we can provide a completion dictionary without shipping/requiring the auto complete package as a dependency?

Would that be useful or a viable solution?

**Comment by kostajh** [comment]
(As an aside, noting that @xcwen added company mode support today.)

**Comment by ejmr** [comment]
@trashofmasters Thank you for your input.  Since both you and @syohex think this is a bad idea them I'm ok with droping it---it's not like this project is a dictatorship or anything.  I value both of your opinions very highly, so since both of you disagree then than makes me immediately stop to reconsider the entire idea.  And at thiis point, despite my original support, I now need to be convinced/persuaded that the merger of support is worthwhile.

**Comment by ejmr** [comment]
@kostajh Cool, good news to hear about Company Mode support---thanks for the update!

@trashofmasters 

> Alternatively, do you think this integration could be shipped as a separate package...?

That could be a reasonable approach.  It makes me think, you know what would be a nice Elisp package management feature?  If a package could declare recommended additional/support packages, similar to how packages can declare pre-requisites.  Then we could add metadata into PHP Mode so that when people install it via Emacs' standard package system there could be an easy menu (or such) saying, "Hey here are some really useful extra packages that extend PHP Mode".  I'm just brainstorming, not suggesting we make any changes to `package.el` for this, heh.

At the very least, I think we would all probably agree that placing a list of useful PHP Mode-related packages and extensions in the README---near the top so users will be more likely to see them---would be a good idea.  Any disagreements?

**Comment by kostajh** [comment]
+1 for listing packages on the README. I agree with others that `ac-php` shouldn't be included in `php-mode`.

**Comment by redbeardcreator** [comment]
I'd add `flycheck` as a suggestion in the README.

**Comment by syohex** [comment]
I have updated document. Please report us if you know the package which should be listed in README.
