### ISSUE TITLE
 "Eval error in the `c-lang-defconst' for `%s' in %s:" 

### ISSUE THREAD

**Issue by thjwong** [ejmr/php-mode#286]
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" ".emacs")
  signal(file-error ("Cannot open load file" "no such file or directory" ".emacs"))
  byte-code("\303\304	#\210\305!\210\306\n@\nA\"\207" [sym mode err message "Eval error in the `c-lang-defconst' for `%s' in %s:" makunbound signal] 4)
  c-get-lang-constant(c-mode-menu (cc-langs \.emacs stan-mode stan-mode) php-mode)
  byte-code("\301\302\303\304\305\306\307\310#B$\207" [php-mode-map easy-menu-do-define php-mode-menu "PHP Mode Commands" "PHP" c-get-lang-constant c-mode-menu (cc-langs \.emacs stan-mode stan-mode) php-mode] 9)
  #<subr require>(php-mode nil nil)
  ad-Advice-require(#<subr require> php-mode)
  apply(ad-Advice-require #<subr require> php-mode)
  require(php-mode)
  eval-buffer(#<buffer  *load*> nil "c:/Users/abcroadie/.emacs" nil t)  ; Reading at buffer position 28677
  load-with-code-conversion("c:/Users/abcroadie/.emacs" "c:/Users/abcroadie/.emacs" t t)
  load("~/.emacs" t t)
```

Of course .emacs is there at ~/
It happens on GNU Emacs 24.5.1 (i686-pc-mingw32) on a Windows-7 64-bit. Doesn't have the same problem on a Windows 10 64-bit, nor on Linux.

**Comment by syohex** [comment]
Could you reinstall and retry after removing `php-mode`(and remove byte-compiled file of .emacs if you byte-compile it) ?

**Comment by thjwong** [comment]
Thanks for your quick reply.
There was no byte-compiled .emacs file... and my installation for 3+ times was not so clean every time using M-x package-install or through the M-x package-list-packages interface. Finally after reading your reply, I removed the package and installed the latest tar file downloaded from MELPA using M-x package-install-file.

And it has been working without problem now.
