### ISSUE TITLE
Strange indentation in a strange case.

### ISSUE THREAD

**Issue by JulienPalard** [ejmr/php-mode#287]
We're having an indentation problem in a file, so @mouchimotte and I spent a few long minutes to minimize it to its shortest version, and here it is:

```
<?php

function foo()
{
    preg_match('[\'""ff]');

    if (TRUE)
    {
    echo 42;
}
    return $ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
}
```

(sha1 sum 7ab24da6695f76a40a23e201dabca5d387362278)

Fun facts:
- If we reduce the number of letters in the return variable name, the bug dissapear.
- If we swap the brackets in the string to be `'\'""ff[]'`, `echo 42` is now indented  by 15 spaces
- If we replace preg_match with `$quote = '\'""ff[]';` the the bug persists.

We're using version 1.17.0 from melpa-stable, we're using `php-enable-psr2-coding-style`.

**Comment by ejmr** [comment]
Thank you for the bug report.  I can duplicate the error, so I will put it on my list of things to do.  Having said that, I just moved over 1,000 miles this month for a new job, so I apologize in advance if I don't end up spending time on PHP Mode bugs for the rest of the calendar year.

**Comment by JulienPalard** [comment]
We're developpers here, so if you have any pointers to give us, we may check it ourself, but we only know lisp, clearly not mastering it, we haven't read the php-mode code a single time, not sure we can help :(

**Comment by JulienPalard** [comment]
I do no longer have the bug with emacs25.1.1 and php-mode 1.18.2, closing this.
