### ISSUE TITLE
php-mode fails on git HEAD for emacs

### ISSUE THREAD

**Issue by hexmode** [ejmr/php-mode#290]
Using c463dd01c78224c450cb8be823e6ac524ba39ce6 from emacs, I get the errors until I make the following changes in php-mode.

```diff
diff -ub php-mode.el\~ php-mode.el
--- php-mode.el~	2016-01-10 17:08:08.000000000 -0500
+++ php-mode.el	2016-01-10 17:17:14.862451651 -0500
@@ -1336,8 +1336,8 @@
 (defconst php-font-lock-keywords-1 (c-lang-const c-matchers-1 php)
   "Basic highlighting for PHP mode.")
 
-(defconst php-font-lock-keywords-2 (c-lang-const c-matchers-2 php)
-  "Medium level highlighting for PHP mode.")
+;; (defconst php-font-lock-keywords-2 (c-lang-const c-matchers-2 php)
+;;   "Medium level highlighting for PHP mode.")
 
 (defconst php-font-lock-keywords-3
   (append
@@ -1370,7 +1370,7 @@
      ("\\sw+::\\(class\\)" 1 font-lock-constant-face))
 
    ;; cc-mode patterns
-   (c-lang-const c-matchers-3 php)
+;;   (c-lang-const c-matchers-3 php)
 
    ;; php-mode patterns *after* cc-mode:
    ;;   most patterns should go here, faces will only be applied if not

Diff finished.  Sun Jan 10 17:22:20 2016
```

**Comment by syohex** [comment]
Sorry too late reply. When did you get error ? At loading ?

**Comment by hexmode** [comment]
Syohei YOSHIDA writes:

> Sorry too late reply. When did you get error ? At loading ?

Late reply isn't so bad.  At least it is a reply.

Yes, I saw this at loading.  I can rebuild if you want more tests on the
latest emacs.

**Comment by syohex** [comment]
I cannot get any errors by `% emacs -Q -l php-mode.el` on both emacs-25 branch and master branch which are built at `2016/JAN/18`.

Could you reinstall latest version and test this ?

**Comment by hexmode** [comment]
I don't get the errors with the latest emacs.
