### ISSUE TITLE
Comments starting with # will not be recognized as comment-face, with // it will.

### ISSUE THREAD

**Issue by ReneFroger** [ejmr/php-mode#302]
Tested with Emacs 25.0.50 on Ubuntu 15.10, with the latest relase of PHP-mode.

`font-lock-comment-face` will be applied on comments starting with `//`. But this is not the case for comments starting with `#` while they're considered as comment tags by the PHP interpreter.

**Comment by syohex** [comment]
Could you show us sample code of this issue ?

**Comment by ReneFroger** [comment]
Sure:

`<php
// example
# test
`

**Comment by syohex** [comment]
![php-comment](https://cloud.githubusercontent.com/assets/554281/14592430/61392a2c-0559-11e6-9879-4a0d4bb7e805.gif)

I cannot reproduce this issue.

**Comment by ReneFroger** [comment]
I tested with the empty Emacs init.file, in Emacs 25.0.50:

![test](https://cloud.githubusercontent.com/assets/5211845/14769443/77297112-0a58-11e6-8ad2-030d4780d39b.gif)

I guess your PHP-mode will be then the default mode?  By the way, there was an warning about missing specification:

    File mode specification error: (void-function c-restore-<>-properties)

But I guess it's not related with the comment face, since it's a C-mode function? Any suggestion to debug the missing comment face further?

**Comment by syohex** [comment]
25.0.50 is older version. Could you use latest development version or pretest version or stable version and retry ?

**Comment by ReneFroger** [comment]
Upgrading to the latest development version seems to solved my issue. I really appreciate all your contributions to PHP-mode and the Emacs community, syohex!
