### ISSUE TITLE
$this and $that font-lock keywords are not constrained

### ISSUE THREAD

**Issue by phil-s** [ejmr/php-mode#305]
https://github.com/ejmr/php-mode/blob/master/php-mode.el#L1331

     ;; Highlight special variables
     ("\\$\\(this\\|that\\)" 1 font-lock-constant-face)

This pattern matches any variable starting with `$this` or `$that`.

e.g. `$this_item` has the `$this` part incorrectly highlighted.

This particular instance is presumably fixed like so:

     ("\\$\\(this\\|that\\)\\_>" 1 font-lock-constant-face)

I haven't tried to establish whether this is an isolated issue, or indicative of a more widespread problem.

**Comment by syohex** [comment]
Thanks for reporting issue. I have applied your patch at #306. Please check latest version.
