### ISSUE TITLE
XDebug support?

### ISSUE THREAD

**Issue by d9k** [ejmr/php-mode#313]
I'm new to spacemacs and I would like to ask how good xdebug support in spacemacs is?
I'm interested in visual representation of debugging process at the file edit buffer (for example, breakpoints shown as red circles symbols near the lines numbers and arrow symbol appointed at currently debugged line). Also I would like to see good keymapping, for example F10 for step over, F5 for continue. Eval expression functionality (with ability to copy result)

Upd: sorry, wrong thread, moved to https://github.com/syl20bnr/spacemacs/issues/6732

**Comment by syohex** [comment]
Please check https://github.com/ahungry/geben

**Comment by MarkRedeman** [comment]
@d9k fyi there is an open pull request [adding geben to the php layer](https://github.com/syl20bnr/spacemacs/pull/6376).
