### ISSUE TITLE
Point is moved to the last apostrophe in the file when php-mode is activated

### ISSUE THREAD

**Issue by aaronbieber** [ejmr/php-mode#314]
When `php-mode` first loads in a new buffer, point is left immediately after the last apostrophe in the file. This is in "GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.2.0)" and appears to be caused by the `re-search-forward` in `php-syntax-propertize-function`.

I will have a patch up for this shortly.

**Comment by codingquark** [comment]
Thanks a lot for this!
