### ISSUE TITLE
syntax entry for dollar sign

### ISSUE THREAD

**Issue by mallt** [ejmr/php-mode#320]
While using avy-goto-word-1 (https://github.com/abo-abo/avy) I noticed I couldn't jump to the first letter of php variables. After setting the dollar sign as symbol constituent with

`(modify-syntax-entry ?$ "_" php-mode-syntax-table)`

avy-goto-word-1 starting working as expected.

Would this be a correct addition to the php-mode-syntax-table?

**Comment by syohex** [comment]
[Note] shell-script-mode sets `$` as expression prefix class, while perl-mode sets `$` as escape class.

I'll check other programming languages modes.

**Comment by syohex** [comment]
`ruby-mode` sets `$` as prefix class.

**Comment by mallt** [comment]
Thank you @syohex! I checked your modification with avy-goto-word-1 and it works as expected now.

**Comment by syohex** [comment]
I have merged

**Comment by mallt** [comment]
@syohex I noticed this change causes `(thing-at-point 'symbol)` to drop the dollar sign from variables. Reading https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html, wouldn't it be better to classify the dollar sign as a symbol constituent?

Thanks!

**Comment by zonuexe** [comment]
@mallt 
I do not agree with confusing users by changing syntax-table.
As an alternative, I implemented `(thing-at-point 'php-token)`. 
(https://github.com/zonuexe/php-util.el/commit/218ad43944ba534edbe9ec1c4ec904620d6871a1 is in my private package, but if this function is seems to stabilize, I propose to integrate it into php-mode.)

Is this what you expected?

**Comment by mallt** [comment]
I was just thinking that if `(thing-at-point 'symbol)` doesn't return the expected result the syntax table might not be correct. To me it seems the dollar in php is rather a symbol constituent than an expression prefix, but I guess there are no strict rules to follow here.
