### ISSUE TITLE
PHP mode fails to launch

### ISSUE THREAD

**Issue by tigerhawkvok** [ejmr/php-mode#324]
PHP mode fails to launch with the following error

![image](https://cloud.githubusercontent.com/assets/165937/19839950/0edbf478-9ea9-11e6-8804-2cbc7efb6a00.png)

This occurs on both new files and opening existing ones.

This occurs for version

```
GNU Emacs 25.1.1 (x86_64-w64-mingw32)
 of 2016-09-17
```

**Comment by mallt** [comment]
Hi @tigerhawkvok, this seems to be the same issue as in https://github.com/ejmr/php-mode/issues/322.
Removing old .elc files should fix it, or maybe setting `(setq load-prefer-newer t)` could help as well.

**Comment by tigerhawkvok** [comment]
@mallt `load-prefer-newer` didn't work, but deleting the `php-mode` directory and reinstalling php mode did the trick. Thanks!
