### ISSUE TITLE
font-lock-doc-face?

### ISSUE THREAD

**Issue by bjd-pfq** [ejmr/php-mode#327]
Not an issue, but a question: why is it that php-mode does not provide a distinct face for font-lock-doc-face for /**  */ style comments for doc strings (like js2-mode and elisp mode do)?

**Comment by syohex** [comment]
Because php-mode does not implement such comment highlighting. php-mode is implemented based on c-mode and php-mode does not have own comment highlighting.

**Comment by bjd-pfq** [comment]
I was thinking not of comment code, but of DocBlock:
see here:
https://en.wikipedia.org/wiki/PHPDoc


I currently have my emacs configured for Javascript to have a grey
comment face (regular //-style and /* */ -style comments, and another
face for JsDoc documentation in /**  */-style blocks.

I really don't see why php-mode could not have that, since PHPDoc is
a known Doc format.

Your answer seems more or less self-referential: it doesn't have it
because ... it doesn't have it.

Thanks.

bjd



Syohei YOSHIDA wrote on 01/03/2017 02:02 AM:

**Comment by zonuexe** [comment]
@bjd-pfq 
As you say,  it behaves is strange which PHP's doc block doesn't have `font-lock-doc-face`.
php-mode uses `c-doc-comment-style` based on CC-mode (defined in `cc-vars.el`).

```
(c-doc-comment-style . javadoc)
```

When using this function, cc-mode has the ability to treat it as doc-comment.
However, in reality it will appear as font-lock-comment-face.

### java-mode

<img width="792" alt="2017-01-03 14 42 44" src="https://cloud.githubusercontent.com/assets/822086/21600631/ef023bec-d1c2-11e6-816e-a00fafbec000.png">

### php-mode

<img width="796" alt="2017-01-03 14 42 21" src="https://cloud.githubusercontent.com/assets/822086/21600630/eefd51fe-d1c2-11e6-831e-b57674682c0d.png">

I will investigate the cause of this problem.

**Comment by zonuexe** [comment]
@bjd-pfq Has your issue been solved?

**Comment by ejmr** [comment]
As of #329 I feel like this can be closed.
