### ISSUE TITLE
php-mode: v1.17.0 Error `recursive load` in spacemacs

### ISSUE THREAD

**Issue by jmjoy** [ejmr/php-mode#328]
Recursive load

**Comment by syohex** [comment]
This is same as #269.

And I cannot reproduce on Emacs 24.5 and 25.1 and 26(development version). If you upgrade Emacs version, please reinstall php-mode. Byte-compile file which is compiled by older emacs may cause this issue.

NOTE: Please show us your environment(Emacs version, operating system, minimum configuration which reproduces your issue etc).
