### ISSUE TITLE
Buffer change w/o making an actual change.

### ISSUE THREAD

**Issue by akenich** [ejmr/php-mode#331]
Running PHP mode 1.17.0 of 2015-06-23 on Mac OS El Capitan.
emacs 25.1

When I open a file with this contents (*):
/* "

Even if I do not make a change to the file, emacs reports that the buffer has changed. As you can see from the attached video, the buffer file that is created is identical to the original file.

Please see attached video:
![php_mode](https://cloud.githubusercontent.com/assets/1140620/22183003/8811378a-e0b3-11e6-9f17-593e9fa3cd5c.gif)

* Note: This content can be anywhere in the file, and this problem will occur. 

I have attached the file in the video here:
[php-mode-change-issue.php.txt](https://github.com/ejmr/php-mode/files/721976/php-mode-change-issue.php.txt)

**Comment by syohex** [comment]
Do you use latest version ? I suppose this issue is fixed by #308.

**Comment by akenich** [comment]
Confirmed. I had installed php-mode via homebrew and that was the latest version available. Now I've upgraded to 1.18.2 and everything works fine, thank you! Case closed.
