### ISSUE TITLE
Severe slow down / lock up when opening or editing a file

### ISSUE THREAD

**Issue by cmack** [ejmr/php-mode#333]
I am using `php-mode-20170126.2227` and `GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-20` and running with `-q` set.

I have a file about 800 lines long that causes Emacs to pause for almost a minute while opening it or when editing it. I haven't been able to reproduce on other php files. Unfortunately I can't share the file nor have I been able to reproduce with a reduced use case. However after profiling it seems to be related to font-locking. Attached is a profile session
[slow-php-cpu.profile.txt](https://github.com/ejmr/php-mode/files/740739/slow-php-cpu.profile.txt)
which can be opened with `profile-find-profile`

I have also tried deleting my php-mode *.elc files without luck. I have also received errors like this but: 
```
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-symbol-char-key’ (fallback source eval - php-mode compiled with CC Mode 5.32.99 but loaded with 5.33): (error "‘c-symbol-char-key’ got no (prior) value in php-mode (might be a cyclic reference)")
```
They usually disappear after byte-recompiling, but I thought I would include since they seem like they could be partly related.

**Comment by syohex** [comment]
Can you reproduce this issue previous version(before merged #329) ? CC: @zonuexe 
And could you show(or upload) us code which reproduces this issue ?

![php-mode](https://cloud.githubusercontent.com/assets/554281/22448389/6fdba246-e79c-11e6-8fb1-8365eeb6f0f9.PNG)

**Comment by zonuexe** [comment]
@cmack Thanks for reporting.  I am going to undertake profiling and optimization.

There is no particular problem with my business code (<6000 lines) and my environment (GNU Emacs 25.1.91.1 (x86_64-apple-darwin15.6.0)), so it is necessary to reproduce the case where the problem occurs.

**Comment by cmack** [comment]
@zonuexe @syohex good news, I found a reduced test that is repeatable! It appears that having `;` in a phpdoc causes the problem. For example:

```php
/**
* @var SomeClassName;  <-- bad semicolon
*/
protected $myVar;
```

Here is the full example file that will lock up emacs:

```php
<?php

namespace SlowNamespace\More\Levels;

use Carbon\Carbon;
use Illuminate\Support\Collection;

class Hello
{
    /**
     * @var ThirdClass;
     */
    protected $fors;

    /**
     * @var FourthClassRepository;
     */
    protected $psr2s;

    public function __construct(
        ThirdClass $for,
        FourthClass $psr2
    ) {
    }
}
```

**Comment by syohex** [comment]
@cmack Could you check latest version ? (If you use MELPA, you need to wait some hours until updating php-mode)

**Comment by cmack** [comment]
@syohex :white_flower: Latest MELPA works for me. Thanks!
