### ISSUE TITLE
php-mode.el: "Warning: `syntax-begin-function' is an obsolete variable (as of 25.1)."

### ISSUE THREAD

**Issue by scfc** [ejmr/php-mode#337]
When byte-compiling `php-mode.el` 1.18.2, Emacs 25.1.1 complains:

    emacs -Q -batch -L . -f batch-byte-compile php-mode.el

    In php-mode:
    php-mode.el:1067:9:Warning: `syntax-begin-function' is an obsolete variable
        (as of 25.1).

**Comment by syohex** [comment]
Because php-mode.el supports older Emacs version.

**Comment by scfc** [comment]
I don't want to remove it :-), but make the code work (without warnings) on all supported Emacs versions.

**Comment by ejmr** [comment]
This is fixed thanks to @zonuexe but my apologies for the patch falling off the radar and going unmerged for so long.
