### ISSUE TITLE
Feature request: add faces for syntax elements

### ISSUE THREAD

**Issue by Fuco1** [ejmr/php-mode#344]
Instead of using `font-lock` faces directly, it would be better to add faces for each syntax element and make them inherit from `font-lock` by default.  This way users can locally modify the faces without having to change the `font-lock` faces globally.

This is usually a standard practice and it shouldn't be very difficult.

**Comment by syohex** [comment]
Can we close this issue by #350 ?

**Comment by ejmr** [comment]
#350 got side-tracked into a different discussion about `$this`, but yes, in my opinion we can close this issue.
