### ISSUE TITLE
use and namespace treated as warning

### ISSUE THREAD

**Issue by silgon** [ejmr/php-mode#358]
Hello,
I just installed php-mode from the melpa packages, and when I'm using either `namespace` or `use` I get the highlighting as if it was a warning as shown in the following picture.

![image](https://cloud.githubusercontent.com/assets/901061/26528913/d90899c0-43b5-11e7-90de-c4ade5b2909e.png)

I was reading the description of the project and you mentioned something related this problem in https://github.com/ejmr/php-mode/blob/master/Changelog.md 

> 1.5.1
> Fix highlighting for namespaces, classes, and traits.

I would like to ask you how to solve it. I'm using emacs 24.5.1 with ubuntu 14.04. Also, the folder containing php-mode is `elpa/php-mode-20170428.1853` installed from the packages list.

Thanks.

**Comment by silgon** [comment]
A bit more information. When I fresh install php-mode it works (I uninstall it and the re-install it), the highlighting works *(as in first image below)*, however when a restart emacs, the highlighting gets bad again *(as in second image bellow)*.
![image](https://cloud.githubusercontent.com/assets/901061/26530645/14817a76-43d9-11e7-894a-90dd8abd2bd3.png)
![image2](https://cloud.githubusercontent.com/assets/901061/26530644/1480860c-43d9-11e7-81c7-7cf2d75d9298.png)
The only information I have for php in my `emacs.rc` is the following:
```lisp
(require 'php-mode)
(add-hook 'php-mode-hook
          '(lambda ()
             (require 'company-php)
             (company-mode t)
             (ac-php-core-eldoc-setup) ;; enable eldoc
             (make-local-variable 'company-backends)
             (add-to-list 'company-backends 'company-ac-php-backend)))
```

**Comment by zonuexe** [comment]
@silgon What is the face of `namespace` and `App`?
You can check the face by pressing <kbd>M-x</kbd> <kbd>describe-char</kbd> (or <kbd>C-u</kbd> <kbd>C-x</kbd> <kbd>=</kbd>) after moving the cursor over the letter.

<img width="740" alt="2017-05-29 2 29 14" src="https://cloud.githubusercontent.com/assets/822086/26530819/473af88c-4417-11e7-9641-4c567aa49595.png">

**Comment by silgon** [comment]
Thanks for replying. For fresh installed `php-mode` I get: 
```
There are text properties here:
  face                 php-keyword
  fontified            t
```

After I restart is the following:
```
There are text properties here:
  face                 font-lock-warning-face
  fontified            t
```

**Comment by ejmr** [comment]
Nothing in your `emacs.rc` looks like it should affect the font-lock highlighting after the restart.  And just to be clear, when you say restart, you mean you are completely closing Emacs and then restarting it?  I ask because I want to be able to reproduce this bug.

**Comment by silgon** [comment]
Yes. I close emacs and reopen it. For re-installation of php-mode, I close emacs, delete the folder `elpa/php-mode-*` (in this case `elpa/php-mode-20170428.1853`), reopen emacs, reinstall `php-mode` and reopen the file, this is the case when I see the correct highlighting.

**Comment by silgon** [comment]
@zonuexe  yes, sorry for the sometimes nasty code =).

**Comment by ejmr** [comment]
@silgon I apologize for the very late response, but in the time since you first reported this problem we have introduced some bug fixes related to namespaces and classes, and bumped the version number a few times.  Please let us know if you continue to have this problem.  And if so I will make an effort to address it more quickly this time.

**Comment by silgon** [comment]
I haven't being coding in php since last time =). So, I updated the package to `php-mode-20170621.2242` from melpa. Still the same problem. It's actually not working anymore when I re-install it. Do you have any ideas how to debug it?

**Comment by ejmr** [comment]
PHP Mode just *entirely* stopped working?  That is pretty serious.  My first guess, gut instinct is that some other package or configuration is causing a conflict.

> Do you have any ideas how to debug it?

Launching the editor via `emacs --debug-init` will enable Emacs' built-in debugger to investigate any potential problem that's taking place on start-up.  It may also be worth trying `emacs -q --debug-init` and manually executing `(require 'php-mode)` to see if that works, i.e. testing the package in isolation basically.

**Comment by silgon** [comment]
no no, only the highlighting of the namespace and so on. What it is not working anymore when I reinstall is the highlighting. Before, with the previous version, when I was reinstalling `php-mode` the highlighting was working fine the first time, after rebooting emacs it was not working anymore, that's what it is not working. Sorry if I express myself incorrectly =)

**Comment by zonuexe** [comment]
In general, face is overwritten by minor mode. I saw faces changed by [flycheck](https://github.com/flycheck/flycheck), [beacon-mode](https://github.com/Malabarba/beacon) etc, but I have not experienced the same problem.

(I am sorry, I have not got time yet and I have not scrutinized your init.el.)

**Comment by silgon** [comment]
thanks @zonuexe , I'll debug by disabling some minor modes tonight or tomorrow and I'll let you know the results =)

**Comment by silgon** [comment]
It was all my mistake. I was playing around today with the configuration as promised. There was an old file of the `php-mode` that was overriding some properties of the `php-mode` from melpa files. The file was so old, I forgot it existed. Thanks @zonuexe  and @ejmr for the help, and sorry for wasting your time in an error that was 100% from my side. =)

**Comment by ejmr** [comment]
No need to apologize.  Glad to hear the problem is resolved :)
