### ISSUE TITLE
Recursive load error

### ISSUE THREAD

**Issue by bowenchen6** [ejmr/php-mode#359]
In toplevel form:
php-current.el:33:1:Error: Recursive load: "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.elc", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.elc", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.elc", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.elc", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.elc", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el"

emacs version is 24.5.1

**Comment by ejmr** [comment]
Sorry that you ran into a problem, but thank you for the bug report and useful information.

@zonuexe `skeleton/php-current.el` does not need `(require 'php-mode)`---right?  At a glance that looks like the problem, and I believe removing the `(require ...)`'s will fix things.  But since you contributed that file I wanted to ask before `git push`-ing a simple patch deleting those lines.

**Comment by bowenchen6** [comment]
OK, I send  a pull request.

**Comment by bowenchen6** [comment]
**Also a error I found just now**:
php-mode.el:997:1:Error: Recursive load: "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el", "/home/user/.emacs.d/elpa-24.5/php-mode-20170609.1728/php-mode.el"

**Comment by zonuexe** [comment]
Hmm... That change probably resolves your problem, but it certainly depends on php-mode, so I do not think its `require` is unnecessary.

**Comment by zonuexe** [comment]
I put `php-current-*` function in skeleton according to the proposal in https://github.com/ejmr/php-mode/pull/323 , but I think that the affinity of this function with skeleton is not good.

I think to revert this function to https://github.com/ejmr/php-mode/pull/323/commits/3a7239677eee64fe0d870b4d467f5487913f89bd .  As a side effect of moving this function to `php-mode.el` your problem will probably be resolved.  (However, it is not essential problem solving.  That environment may have another problem not related to php-mode.)

**Comment by bowenchen6** [comment]
ok

**Comment by ejmr** [comment]
Fixed thanks to @zonuexe and you can see more details in the merge commit above.
