### ISSUE TITLE
New Co-maintainer to Replace Me

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#365]
Please read [this /r/emacs post](https://www.reddit.com/r/emacs/comments/6pchsm/request_the_future_of_php_mode_tldr_near_bottom/) for information about how I cannot continue to maintain this project.  And thank you all for your years of time and hard work making PHP Mode great, which I know you will continue to do without me.

**Comment by glynnforrest** [comment]
Eric, I deeply respect the courage it must have taken to be so candid about your situation.

I'm currently using PHP mode 30+ hours a week, and value it highly enough to be more than willing to step up as new co-maintainer. Funnily enough I [took over the stewardship](https://github.com/syl20bnr/spacemacs/issues/8225) of [salt-mode](https://github.com/glynnforrest/salt-mode) earlier this year, another package I use a great deal. I think I've done a decent job so far: adding tests, helping to add new features, and handling incoming issues in a timely manner.

That mode has far less scope than PHP mode, so before I commit fully I'd like to hear a bit more about the workload you usually handle maintaining the mode. I'd also like to have a brief chat about future plans and your overall 'vision' so I can help push the project in a direction you'll be happy with.

Thank you for your hard work on PHP mode for all of these years, you are a model member of the emacs community. Some of my first pull requests were on your php-auto-yasnippets repository, and I remember you being very welcoming. Wishing you the very best of luck with your recovery.

**Comment by ejmr** [comment]
> Eric, I deeply respect the courage it must have taken to be so candid about your situation.

Thank you.

> I think I've done a decent job so far: adding tests, helping to add new features, and handling incoming issues in a timely manner.

I definitely agree.  Especially when it comes to that first part about tests.  In my opinion any maintainer(s) should focus a good chunk of their effort on them.  Which I say hypocritical because I've been guilty of not doing it myself.

I read through the Git history for Salt Mode and saw only one thing which I would comment on: [your commit messages can never be too long](52a75c0ec1aa267dc1e362f8eae493225de9e159) especially as a maintainer.  I mean, that message dwarfs the patch, and then some, lol.

Tonight or tomorrow I will answer the rest of your questions by reviewing todo lists, brainstorm notes, etc., so I can give you a clearer idea of where things are and what you should expect as far as dealing with pull requests.

Until then, thanks again!

> Some of my first pull requests were on your php-auto-yasnippets repository...

I remember that, lol, from the Summer of 2013 if I remember correctly.  Something about `$_SERVER`, some problem around it.  Man I have a great memory for relatively useless facts...  Heh.

**Comment by glynnforrest** [comment]
> one thing which I would comment on: your commit messages can never be too long

Agreed. I'll admit that the salt-mode commit messages don't meet the standard expected in this project. Since PHP mode is a larger and more popular project, I would include a higher level of detail in messages, especially for any user-visible changes. As salt-mode grows in popularity I'll be less gung-ho about messages there too.

Since this project is co-maintained, perhaps now is as good a time as any to set up a github organisation and migrate the mode away from a personal github account. I appreciate it may cause a slight pain with melpa, but there are ways around that.

Looking forward to hearing your thoughts.

**Comment by ahonnecke** [comment]
Thank you Eric and I'm sorry to hear about your health.

I'd be happy to help you glynn with the co-maintenance of php-mode in any way I can, (I'm also using it 30+ hours a week), however I've not maintained any oss anything before.  Also, my lisp is pretty rusty.

**Comment by NateEag** [comment]
@ejmr, as I said on Reddit, I'm really sorry to hear about your health issues.

I have actually just started using php-mode again for the first time in years.

With two small children, I have far less free time than I did when I was last writing PHP, so I can't really offer co-maintainership, but I've been hoping to make a few contributions as I knock the rust off my old PHP setup.

I'd be happy to have admin access to the project, so I could help out if and when I have time, but I realize that should arguably only come with a commitment to actually use it.

I think @glynnforrest's suggestion of making a GitHub organization might be helpful with managing co-maintainership in the long haul.

I vaguely remember feature requests coming up in the past that didn't quite fit into php-mode proper, so perhaps an `emacs-php` organization might make sense, where custom features and prototypical extensions could be collectively owned by the org?

Again - @ejmr, thanks for your dedication and care on this (and other) projects. It is greatly appreciated.

**Comment by ejmr** [comment]
@syohex I would be incredibly grateful if you would please consider becoming the lead maintainer of PHP Mode.  If you choose to take on that role, I will also support anyone you recommend for co-maintainer(s), because I have always trusted your judgement over PHP Mode decisions.  I also think @NateEag has a great idea about creating an "emacs-php" GitHub organization and would like to know what you think about that.

@zonuexe You have provided so many great patches and additions and fixes in recent history that I would also be happy to see you take a more involved role in helping keep this project alive and running without me.

**Comment by codingquark** [comment]
So sorry to hear about your health. You're brave the way you discussed your situation on Reddit. I was aghast.

I have been using php-mode for last ~2 years. I have never been able to contribute to the project because I do not know elisp (can barely get my emacs config to work).

I saw the discussion about donations on the reddit thread. While I learn elisp (which is very slow), I am willing to donate to the project. I am sure many others would be too. I think this should also be discussed. I feel that I need to give back to this package as it is so useful to me. But I don't have the skills to code for it. And being able to donate whatever little I can afford will at least give me the feeling of helping others indirectly. It's not ideal, but it is something.

**Comment by ejmr** [comment]
@codingquark 

> I have never been able to contribute to the project because I do not know elisp.

Reporting bugs helps tremendously.  So does reporting feature requests so that all of the developers have an idea of want the community wants most out of PHP Mode.  In my mind those are absolutely as necessary as programming, and you can help the project a great deal that way if you want.

> ... I am willing to donate to the project. I am sure many others would be too. I think this should also be discussed.

I will leave it to future maintainers to decide whether or not to accept dontations.  Personally, I will not accept them though; but I also have no problem with other developers doing so.  I am very low on the kidney transplant list and most likely will die in a couple of years before receiving at least.  I cannot in good conscience accept any donations knowing I have very little chance to live for another 24--36 months.

But thank you very much for the offer.  Just because you do not know Emacs Lisp, do not let that stop you from improving the project, even if it's only through bug reports---they are huge helps.

**Comment by codingquark** [comment]
@ejmr 

>Reporting bugs helps tremendously. So does reporting feature requests so that all of the developers have an idea of want the community wants most out of PHP Mode.

I understand. I will try my best then!

>I will leave it to future maintainers to decide whether or not to accept dontations. Personally, I will not accept...

Salute!

I have a few ideas in mind already, to help improve. Thanks for the pointers, encouragement and help. :)

**Comment by zonuexe** [comment]
@ejmr Thank you for mention.

I am always interested in improving PHP coding in Emacs.
I promise to continue to contribute to php-mode.

**Comment by glynnforrest** [comment]
I agree with both proposals here: to set up an `emacs-php` organization, and to have someone already experienced with the project become maintainer (@syohex, @zonuexe, etc).

**Comment by ejmr** [comment]
@glynnforrest Please see 009293a1133641862bf6f3e3a3afb5a374d12ccd for a start on answering some of the more detailed questions you had.

**Comment by ejmr** [comment]
@syohex Also please consider becoming the lead maintainer as a favor to a fellow B'z fan.  :wink: Unless you think *In the Life* was a better album than *Brotherhood.*  In which case---eh, no, there's no way you would think that.

**Comment by NateEag** [comment]
I just noticed that there exists an [emacs-php org](https://github.com/emacs-php/), of which @zonuexe appears to be the sole member.

I hadn't realized one existed when I suggested creating it. 

Would it be reasonable to look at moving php-mode to that organization and adding some people to it?

If not, no worries - I just stumbled across the org by accident and thought of this thread.

**Comment by ejmr** [comment]
@NateEag I think it is a good idea.  @zonuexe has done a lot for PHP Mode in recent months, so to me it makes sense for him to be a member of that organization.  If @syohex aggrees to the idea then I would be happy with turning over ownership of the repo to the emacs-php org.  Note that I'm *not* implying @syohex or anyone else has to join the organization; I just want his explicit consent before changing the ownership of a repository to which he has full and complete control.  It would be in very poor taste for me to make that change otherwise.

**Comment by NateEag** [comment]
@ejmr Yep, makes perfect sense.

I just happened to notice it and figured I'd ask.

**Comment by ejmr** [comment]
So it turns out that GitHub does *not* allow someone to list an organization as a "collaborator".  I can, apparently, transfer the ownership to @emacs-php, which at this point feels like the best idea.  However, I've still not heard anything from @syohex and I really, *really* do not want to make that decision without first hearing his thoughts.  That said, something needs to change soon.  I have multiple pull-requests that I was in the process of dealing with when unexpectedly I had to be hospitalized last week.  Unless @syohex raises any objections then I am going to transfer that ownership at a minimum of thirty days from now, because there are users out there who need important bug fixes and contributions merged, and I am literally becoming too sick to do this very much longer.  Things like #370, #371, #372, #373, and #374 are long overdue.  And if I cannot deal with them in a timely manner then at the very least it is my responsibility to find someone who can.

**Comment by zonuexe** [comment]
I am sorry that I did not express a clear intention for a while.
Meanwhile I was thinking of the best way to develop PHP.  As you know, I have started a few actions.

I am short of experience, but I am ready to take over ownership.
I have tasks within a few weeks ([PHP Conference Japan](http://phpcon.php.gr.jp/2017/), for example) but I will work on dealing with problems as soon as possible.

**Comment by ejmr** [comment]
@zonuexe No need to apologize; I am waiting until the end of October to transfer ownership anyway, and part of that reason is because it gives us time to work out any relevant issues, e.g. if you have any questions about maintaining PHP Mode overall then please don't hesitate to ask.

Also have fun at the conference.  Coincidentally, Japanese is my second language; I would have a lot of fun giving a talk there about how to use GNU Emacs for modern PHP development, heh.

**Comment by syohex** [comment]
@ejmr Sorry very very belated reply, I'm very busy in this half year. 
I consider this issue at this weekend.

(Recently I rarely use Emacs now...)

**Comment by ejmr** [comment]
@syohex Just like I told @zonuexe, no need to apologize friend.  Thank you for considering the issue, and I look forward to your thoughts and insight.

**Comment by ejmr** [comment]
I have closed this issue since the change in maintainers will happen per #387.  Thank you, again, to everyone here for the discussion and considerations.  I am forever indebted to all of you.
