### ISSUE TITLE
Can't use ggtags to jump to definition in `use` statements or FQN 

### ISSUE THREAD

**Issue by martin-brainlabs** [ejmr/php-mode#386]
Something in the recent commits has caused `M-b` and `M-f` to see a FQN classname (e.g. `League\Csv\Reader` as a single word. This also causes [ggtags](https://github.com/leoliu/ggtags) to not be able to jump to its declaration with `M-.`. I haven't been paying attention to recent updates, so I'm not sure if this is as intended.

**Comment by zonuexe** [comment]
@martin-brainlabs Thank you for reporting.

That is because of changing the definition of the syntax table in #383 .
