### ISSUE TITLE
Submit to Marmalade Repo

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#39]
This version of php-mode is already in [MELPA](http://melpa.milkbox.net/).  But it would be nice to have in the [Marmalade](http://marmalade-repo.org/) repository as well, which means [editing the header somewhat](http://marmalade-repo.org/packages).

**Comment by syohex** [comment]
We have [MELPA stable](http://stable.melpa.org/#/) now.
Developers uses it for releasing stable version.
We can update to MELPA stable by tagging(like `git tag`).
(We need not to upload files manually).

**Comment by ejmr** [comment]
I am going to close this because I tried submitting PHP Mode to Marmalade and that went nowhere.  It's already there but it's quite an old version.  Now that we have MELPA stable I would rather make use of Git tags for that.
