### ISSUE TITLE
Bump version v1.18.4

### ISSUE THREAD

**Issue by zonuexe** [ejmr/php-mode#393]
If the current revision seems to be stable, tag it as stable version.

The release will be done after confirming that some issues have ceased to reoccur.

- #386
- #389
- #390

However, we are aware of some problems that we have not yet solved.

- #280 #383  
- #384 #385 

**Please report any other known problems.**

**Comment by calbrecht** [comment]
@zonuexe sorry for the inconvenience, i guess #280 #383 could be solved by changing the syntax for backslash from word to symbol within last line of php-unescape-identifiers in #383. 

For #384 #385 the description given in #389 was the reason for the changes i made, and as @ahungry writes in the fourth comment,  it fixes the issue but only if checked out and loaded from the cloned repository. So we'll have to find out why it is not fixing the issue through the melpa package.

**Comment by zonuexe** [comment]
@calbrecht Thank you for your reply.
Your changes are awesome, so verify again after a stable release.
