### ISSUE TITLE
File mode specification error: (void-function php-unescape-identifiers)

### ISSUE THREAD

**Issue by gjm** [ejmr/php-mode#394]
Hi.

I get this error after updating the latest melpa version (20171129.2002).

**Comment by zonuexe** [comment]
@gjm Thank you for reporting.

This function `php-unescape-identifiers` was in the previous release. Usually it is solved by updating the package (or recompiling the Lisp file) and/or restarting Emacs.

**Comment by zonuexe** [comment]
@gjm Has your problem been solved?

**Comment by gjm** [comment]
Yes it has. I had some trouble recompiling the package, don't know why, but
after some fiddling got it working.

I'm very sorry for not giving feedback.

Keep up the great work!



Gonçalo Marrafa

**Comment by zonuexe** [comment]
I am glad to hear that. Thank you!
