### ISSUE TITLE
delayed font-locking issue

### ISSUE THREAD

**Issue by mallt** [ejmr/php-mode#414]
When using melpa version 20180205.2247 I'm noticing delayed font-locking as shown in the screencast:

![php-mode-font-lock](https://user-images.githubusercontent.com/8885691/35999846-6712d2c8-0d21-11e8-9bbc-fa9adc4cc94a.gif)

When killing and yanking some parts of the code it seems the font-locking gets activated. Has anyone else experienced a similar issue?

I'm running GNU Emacs 27.0.50 (master branch).

Thanks!

**Comment by MarTango** [comment]
This problem is very easy to replicate, even with `emacs -Q`

**Comment by zonuexe** [comment]
@mallt @MarTango 
Thank you for reporting.
This problem is introduced by #401 .

-----

@fallchildren Do you have any ideas to solve this problem?

**Comment by fallchildren** [comment]
@zonuexe yes, I know what the problem is. I will make a pull request. The problem is `c-before-font-lock-functions` not including `c-change-expand-fl-region`.

**Comment by mallt** [comment]
The issue has been fixed in the latest melpa version. 

@fallchildren @zonuexe Thanks a lot for being so responsive!
