### ISSUE TITLE
Coding style not applied?

### ISSUE THREAD

**Issue by roxlu** [ejmr/php-mode#441]
I've added these lines to the bottom of my init.el but when I describe the c-indentation-style variable it says PEAR is still used.  These are the lines I've added:

`(require 'php-mode)
(add-hook 'php-mode-hook 'php-enable-drupal-coding-style)`

**Comment by roxlu** [comment]
I've found a work-around:  https://gist.github.com/roxlu/40c660d0eae30ab6e21359f592d6cc0c

**Comment by zonuexe** [comment]
@roxlu Thanks to your reporting, and I apologize that I missed your report for a week.
This problem is obvious, so I will fix it shortly.

**Comment by zonuexe** [comment]
@roxlu 
Perhaps even if you abolish the eval-after-load work-around, it will work.
Thanks!

**Comment by gentcys** [comment]
After updated php-mode package `20180326.629`, indent 2 spaces always.
This is php-debug-mode message:

    --- PHP-MODE DEBUG BEGIN ---
    PHP Mode 1.19.0 of 2018-03-26
    versions: GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 
    13F1911))
     of 2017-04-21; PHP Mode 1.19.0 of 2018-03-26
    major-mode: php-mode
    minor-modes: (dumb-jump-mode dired-isearch-filenames-mode diff-hl-dired-mode ido- 
    everywhere switch-window-mouse-mode rainbow-mode yas-minor-mode macrostep-mode 
    flymake-mode flycheck-color-mode-line-mode elisp-slime-nav-mode aggressive-indent-mode 
    highlight-quoted-mode rainbow-delimiters-mode symbol-overlay-mode bug-reference-prog- 
    mode bug-reference-mode paredit-everywhere-mode paredit-mode goto-address-prog-mode 
    goto-address-mode origami-mode dimmer-mode buffer-face-mode text-scale-mode anzu-mode 
    flycheck-mode recentf-mode ivy-historian-mode historian-mode counsel-mode diredfl-mode 
    dired-hide-details-mode ivy-mode xref-etags-mode company-quickhelp-mode company- 
    quickhelp-local-mode company-search-mode company-mode winner-mode savehist-mode 
    default-text-scale-mode electric-pair-mode auto-revert-tail-mode auto-revert-mode mode-line- 
    bell-mode beacon-mode undo-tree-visualizer-selection-mode undo-tree-mode show-paren- 
    mode page-break-lines-mode whole-line-or-region-local-mode hes-mode guide-key-mode 
    popwin-mode whitespace-cleanup-mode whitespace-newline-mode whitespace-mode diff-hl- 
    dir-mode diff-hl-mode diff-minor-mode diff-auto-refine-mode projectile-rails-mode inf-ruby- 
    minor-mode projectile-mode compilation-minor-mode compilation-shell-minor-mode ibuffer- 
    auto-mode ipretty-mode auto-compile-on-load-mode auto-compile-on-save-mode auto- 
    compile-mode immortal-scratch-mode server-mode prose-mode inferior-js-keys-mode delete- 
    selection-mode cua-mode desktop-save-mode tooltip-mode eldoc-mode electric-quote-mode 
    electric-layout-mode electric-indent-mode mouse-wheel-mode tool-bar-mode paragraph-indent- 
    minor-mode prettify-symbols-mode use-hard-newlines menu-bar-mode file-name-shadow-mode 
    horizontal-scroll-bar-mode jit-lock-debug-mode font-lock-mode blink-cursor-mode window- 
    divider-mode auto-composition-mode unify-8859-on-decoding-mode unify-8859-on-encoding- 
    mode auto-encryption-mode auto-compression-mode temp-buffer-resize-mode visible-mode 
    buffer-read-only size-indication-mode column-number-mode line-number-mode auto-fill- 
    function visual-line-mode transient-mark-mode next-error-follow-minor-mode completion-in- 
    region-mode auto-save-mode auto-fill-mode abbrev-mode overwrite-mode view-mode hs-minor- 
    mode)
    variables: ((indent-tabs-mode nil) (tab-width 4))
    custom variables: ((php-executable /usr/local/opt/php71/bin/php) (php-default-face default) (php- 
    speedbar-config t) (php-mode-speedbar-open nil) (php-template-compatibility t) (php-lineup- 
    cascaded-calls nil) (php-extra-constants nil) (php-do-not-use-semantic-imenu t) (php-site-url 
    https://secure.php.net/) (php-manual-url en) (php-search-url nil) (php-completion-file ) (php- 
    manual-path ) (php-mode-hook (yas-minor-mode (lambda nil (local-set-key (kbd M-P) (quote 
    php-insert-doc-block))))) (php-mode-pear-hook nil) (php-mode-drupal-hook nil) (php-mode- 
    wordpress-hook nil) (php-mode-symfony2-hook nil) (php-mode-psr2-hook nil) (php-mode- 
    force-pear nil) (php-mode-warn-if-mumamo-off t) (php-mode-coding-style pear) (php-mode- 
    enable-project-coding-style t) (php-mode-enable-backup-style-variables t) (php-search- 
    documentation-browser-function nil) (php-class-suffix-when-insert ::) (php-namespace-suffix- 
    when-insert \))
    c-indentation-style: pear
    c-style-variables: ((c-offsets-alist (string . c-lineup-dont-change) (c . c-lineup-C-comments) 
    (defun-open . 0) (defun-close . 0) (defun-block-intro . +) (class-open . 0) (class-close . 0) (inline- 
    open . +) (inline-close . 0) (func-decl-cont . +) (knr-argdecl-intro . +) (knr-argdecl . 0) (topmost- 
    intro . 0) (topmost-intro-cont . c-lineup-topmost-intro-cont) (annotation-top-cont . 0) 
    (annotation-var-cont . +) (member-init-intro . +) (member-init-cont . c-lineup-multi-inher) (inher- 
    intro . +) (inher-cont . c-lineup-multi-inher) (block-open . 0) (block-close . 0) (brace-list-open . 0) 
    (brace-list-close . 0) (brace-list-intro . +) (brace-list-entry . 0) (brace-entry-open . 0) (statement . 
    0) (statement-cont . +) (statement-block-intro . +) (statement-case-intro . +) (statement-case- 
    open . 0) (substatement . +) (substatement-open . +) (substatement-label . 2) (case-label . 0) 
    (access-label . -) (label . 2) (do-while-closure . 0) (else-clause . 0) (catch-clause . 0) (comment- 
    intro c-lineup-knr-region-comment c-lineup-comment) (arglist-intro . +) (arglist-cont c-lineup- 
    gcc-asm-reg 0) (arglist-cont-nonempty c-lineup-gcc-asm-reg c-lineup-arglist) (arglist-close . +) 
    (stream-op . c-lineup-streamop) (inclass . +) (cpp-macro . [0]) (cpp-macro-cont . +) (cpp-define- 
    intro c-lineup-cpp-define +) (friend . 0) (objc-method-intro . [0]) (objc-method-args-cont . c- 
    lineup-ObjC-method-args) (objc-method-call-cont c-lineup-ObjC-method-call-colons c-lineup- 
    ObjC-method-call +) (extern-lang-open . 0) (namespace-open . 0) (module-open . 0) 
    (composition-open . 0) (extern-lang-close . 0) (namespace-close . 0) (module-close . 0) 
    (composition-close . 0) (inextern-lang . +) (innamespace . +) (inmodule . +) (incomposition . +) 
    (template-args-cont c-lineup-template-args +) (inlambda . c-lineup-inexpr-block) (lambda-intro- 
    cont . +) (inexpr-statement . +) (inexpr-class . +)) (c-label-minimum-indentation . 1) (c-backslash- 
    max-column . 72) (c-backslash-column . 48) (c-hanging-semi&comma-criteria c-semi&comma- 
    inside-parenlist) (c-hanging-colons-alist) (c-hanging-braces-alist (brace-list-open) (brace-entry- 
    open) (statement-cont) (substatement-open after) (block-close . c-snug-do-while) (extern-lang- 
    open after) (namespace-open after) (module-open after) (composition-open after) (inexpr-class- 
    open after) (inexpr-class-close before) (arglist-cont-nonempty)) (c-cleanup-list scope-operator) 
    (c-doc-comment-style (java-mode . javadoc) (pike-mode . autodoc) (c-mode . gtkdoc)) (c- 
    comment-prefix-regexp (pike-mode . //+!?\|\**) (awk-mode . #+) (other . //+\|\**)) (c-block- 
    comment-prefix . * ) (c-indent-comments-syntactically-p) (c-indent-comment-alist (anchored- 
    comment column . 0) (end-block space . 1) (cpp-end-block space . 2)) (c-comment-only-line- 
    offset . 0) (c-basic-offset . 4) (c-basic-offset . 4) (c-offsets-alist (arglist-close . php-lineup- 
    arglist-close) (arglist-cont first php-lineup-cascaded-calls 0) (arglist-cont-nonempty first php- 
    lineup-cascaded-calls c-lineup-arglist) (arglist-intro . php-lineup-arglist-intro) (case-label . +) 
    (class-open . 0) (comment-intro . 0) (inlambda . 0) (inline-open . 0) (namespace-open . 0) 
    (lambda-intro-cont . +) (label . +) (statement-cont first php-lineup-cascaded-calls php-lineup- 
    string-cont +) (substatement-open . 0) (topmost-intro-cont first php-lineup-cascaded-calls +)) 
    (indent-tabs-mode) (tab-width . 8) (fill-column . 70) (show-trailing-whitespace . t) (php-style- 
    delete-trailing-whitespace) (c-basic-offset . 4) (c-offsets-alist (case-label . 0)) (tab-width . 4))
    --- PHP-MODE DEBUG END ---
