### ISSUE TITLE
Support Emacs Version

### ISSUE THREAD

**Issue by zonuexe** [ejmr/php-mode#464]
The currently tested version is as follows.

 * 24.3
 * 24.4 - [jessie:`emacs24`](https://packages.debian.org/en/jessie/emacs24)
 * 24.5 - [stretch: `emacs24`](https://packages.debian.org/en/stretch/emacs24)
 * 25.1
 * 25.2 - [stretch: `emacs25`](https://packages.debian.org/en/stretch/emacs25)
 * 25.3
 * HEAD

I am planning to drop tests on **24.3** and **25.1** which are not included in these versions, based on the version provided by Debian.

**Comment by zonuexe** [comment]
@ejmr 
[Unlike PHP](http://php.net/supported-versions.php), Emacs basically has no old stable version or planned maintenance phase.  Many users developing on GNU / Linux are using packages distributed by OS, so I refer to Debian as a representative of distributors.

According to the schedule of [Debian's LTS](https://wiki.debian.org/LTS), the next timing to change the support version is about 2020 when [Jessie](https://www.debian.org/releases/jessie/)'s support is over.  We will consider the support version again around 2020. However, in order to drop support of Emacs 24.5, we may have to judge other OS and another factor.

**Comment by ejmr** [comment]
@zonuexe 

Ah ok, I was not familiar with things with regard to Debian.  Thanks for the info.

**Comment by zonuexe** [comment]
I wrote [Supported Version](https://github.com/ejmr/php-mode/wiki/Supported-Version) article on the wiki.

**Comment by zonuexe** [comment]
Continue to receive comments with this issue, please post if you are requested about supported versions.

**Comment by zonuexe** [comment]
I have found that the `emacs` package of CentOS 7.5.1804 still relies on Emacs 24.3.
Fortunately, we do not have to retract our coding strategy, but we are considering restoring the test for 24.3.
