### ISSUE TITLE
How to produce the block comment ?

### ISSUE THREAD

**Issue by algking** [ejmr/php-mode#468]
I wonder how to produce the block comment format like:

```
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String} firstname Firstname of the User.
 * @apiSuccess {String} lastname  Lastname of the User.
 */
```

When I use C-; to comment the region, I always got 
```
 //@apiParam {Number} id Users unique ID.
 //
 // @apiSuccess {String} firstname Firstname of the User.
 // @apiSuccess {String} lastname  Lastname of the User.

```

**Comment by zonuexe** [comment]
@algking 
Please be aware that <kbd>C-;</kbd> is not a function for generating dock comments.

Commands that forcibly block comment can be easily defined.

```el
(defun php-block-comment (arg)
  (interactive "*P")
  (let ((comment-style 'extra-line)
        (comment-start "/*")
        (comment-end "*/"))
    (comment-dwim arg)))
```

Alternatively, if you do not like `//` style comments, you can assign these variables with `setq-local` in the hook for php-mode.

**Comment by algking** [comment]
@zonuexe  Thanks a lot, I only find the comment-start and comment-end variable, just missing the comment-style.
