### ISSUE TITLE
Question: Why does the mode line show "PHP//l" instead of just "PHP"?

### ISSUE THREAD

**Issue by echosa** [ejmr/php-mode#472]
I haven't been able to figure who where the "//l" in the mode line comes from. 

![image](https://user-images.githubusercontent.com/133786/41169678-50fa37a0-6b0f-11e8-96a3-9fb6421c3ca4.png)

**Comment by zonuexe** [comment]
@echosa 
Current php-mode is an implementation based on cc-mode. Therefore, this mode line is the same as `c-mode` and `java-mode`.
The `l` means [`electric-mode`](https://www.gnu.org/software/emacs/manual/html_mono/ccmode.html#Minor-Modes).

If you are interested in implementing Lisp, please read this code.
- https://github.com/emacs-mirror/emacs/blob/emacs-26.1/lisp/progmodes/cc-cmds.el#L261-L285

**Comment by echosa** [comment]
@zonuexe Ah, electric-mode! Thanks! I didn't realize it would append its mode-line text to the major mode without a space. Thanks!
