### ISSUE TITLE
Fix Highlighting for Multiple Interfaces

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#49]
The code

```php
<?php

class Foo implements Bar, Baz {}
```

fails to correctly highlight `Bar` and `Baz`.  Only one of the two has correct highlighting, while the other is treated like an error.

**Comment by syohex** [comment]
This issue was fixed. 

Here is screenshot with latest version.

![php-mode](https://cloud.githubusercontent.com/assets/554281/5951014/9ef9eaae-a7a4-11e4-9f16-2dc534dfaf98.png)

**Comment by ejmr** [comment]
Thanks again!
