### ISSUE TITLE
Imenu Does Not See Static Methods

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#83]
Consider the following example:

```php
<?php

class Foo
{
        static public function bar() {}
        public function baz() {}
}
```

Imenu only finds and recognizes the `baz` function.  It should also include `bar` under its list of 'Public Methods' and 'All Methods', but fails to do either.

**Comment by syohex** [comment]
This issue was fixed and should be closed.
I can get `bar` and `baz` by `imenu.
