### ISSUE TITLE
Can't load php-mode on OS X

### ISSUE THREAD

**Issue by diegueins680** [ejmr/php-mode#86]
When I use the 2008 version of php-mode.el from the following link I don't have any issues, and Emacs color codes my php code correctly:

    http://php-mode.sourceforge.net

However, when I replace php-mode.el with the current version, emacs displays the following error:
    
    An error has ocurred while loading '~/.emacs':

    File error: Cannot open load file, php-mode

    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file. Start Emacs with the 
    '--debug-init' option to view a complete error backtrace.

This is the output of doing such:

    Debugger entered--Lisp error: (error "Invalid modifier in string")
    eval-buffer(#<buffer  *load*<2>> nil "/Users/dsaa-temp/elisp/php-mode.el" nil$
    load-with-code-conversion("/Users/dsaa-temp/elisp/php-mode.el" "/Users/dsaa-t$
    require(php-mode)
    eval-buffer(#<buffer  *load*> nil "/Users/dsaa-temp/.emacs" nil t)  ; Reading$
    load-with-code-conversion("/Users/dsaa-temp/.emacs" "/Users/dsaa-temp/.emacs"$
    load("~/.emacs" t t)
    #[nil "^H\205\276^@   \306=\203^Q^@\307^H\310Q\202A^@ \311=\2033^@\312\307\31$
    command-line()
    normal-top-level()

**Comment by syohex** [comment]
I cannot reproduce this issue.

Mac users should not use `/usr/bin/emacs`. It is too old(22.1).
Most packages don't work on it.

It is easy to install newer Emacs via homebrew or macports.
I recommend mac users to use them.
